# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/src/qgis/python/pyplugin_installer/qgsplugininstallerrepositorybase.ui'
#
# Created: Sat Jun 23 07:59:43 2018
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_QgsPluginInstallerRepositoryDetailsDialogBase(object):
    def setupUi(self, QgsPluginInstallerRepositoryDetailsDialogBase):
        QgsPluginInstallerRepositoryDetailsDialogBase.setObjectName(_fromUtf8("QgsPluginInstallerRepositoryDetailsDialogBase"))
        QgsPluginInstallerRepositoryDetailsDialogBase.resize(496, 289)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(QgsPluginInstallerRepositoryDetailsDialogBase.sizePolicy().hasHeightForWidth())
        QgsPluginInstallerRepositoryDetailsDialogBase.setSizePolicy(sizePolicy)
        QgsPluginInstallerRepositoryDetailsDialogBase.setStatusTip(_fromUtf8(""))
        QgsPluginInstallerRepositoryDetailsDialogBase.setWhatsThis(_fromUtf8(""))
        self.gridlayout = QtGui.QGridLayout(QgsPluginInstallerRepositoryDetailsDialogBase)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        spacerItem = QtGui.QSpacerItem(351, 23, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem, 5, 2, 1, 1)
        self.label_2 = QtGui.QLabel(QgsPluginInstallerRepositoryDetailsDialogBase)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridlayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_4 = QtGui.QLabel(QgsPluginInstallerRepositoryDetailsDialogBase)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridlayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.editName = QtGui.QLineEdit(QgsPluginInstallerRepositoryDetailsDialogBase)
        self.editName.setObjectName(_fromUtf8("editName"))
        self.gridlayout.addWidget(self.editName, 0, 1, 1, 2)
        self.editParams = QtGui.QLineEdit(QgsPluginInstallerRepositoryDetailsDialogBase)
        self.editParams.setEnabled(False)
        self.editParams.setObjectName(_fromUtf8("editParams"))
        self.gridlayout.addWidget(self.editParams, 3, 1, 1, 2)
        self.buttonBox = QtGui.QDialogButtonBox(QgsPluginInstallerRepositoryDetailsDialogBase)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridlayout.addWidget(self.buttonBox, 9, 0, 1, 3)
        self.label = QtGui.QLabel(QgsPluginInstallerRepositoryDetailsDialogBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridlayout.addWidget(self.label, 0, 0, 1, 1)
        self.labelInfo = QtGui.QLabel(QgsPluginInstallerRepositoryDetailsDialogBase)
        self.labelInfo.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelInfo.sizePolicy().hasHeightForWidth())
        self.labelInfo.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(175, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(175, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.labelInfo.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelInfo.setFont(font)
        self.labelInfo.setFrameShape(QtGui.QFrame.NoFrame)
        self.labelInfo.setText(_fromUtf8(""))
        self.labelInfo.setObjectName(_fromUtf8("labelInfo"))
        self.gridlayout.addWidget(self.labelInfo, 7, 1, 1, 2)
        self.label_3 = QtGui.QLabel(QgsPluginInstallerRepositoryDetailsDialogBase)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridlayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.checkBoxEnabled = QtGui.QCheckBox(QgsPluginInstallerRepositoryDetailsDialogBase)
        self.checkBoxEnabled.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxEnabled.sizePolicy().hasHeightForWidth())
        self.checkBoxEnabled.setSizePolicy(sizePolicy)
        self.checkBoxEnabled.setText(_fromUtf8(""))
        self.checkBoxEnabled.setChecked(False)
        self.checkBoxEnabled.setObjectName(_fromUtf8("checkBoxEnabled"))
        self.gridlayout.addWidget(self.checkBoxEnabled, 5, 1, 1, 1)
        self.editURL = QtGui.QLineEdit(QgsPluginInstallerRepositoryDetailsDialogBase)
        self.editURL.setText(_fromUtf8(""))
        self.editURL.setObjectName(_fromUtf8("editURL"))
        self.gridlayout.addWidget(self.editURL, 1, 1, 1, 2)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout.addItem(spacerItem1, 6, 1, 1, 2)
        self.label_5 = QtGui.QLabel(QgsPluginInstallerRepositoryDetailsDialogBase)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridlayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.layoutAuthCfg = QtGui.QHBoxLayout()
        self.layoutAuthCfg.setSpacing(6)
        self.layoutAuthCfg.setObjectName(_fromUtf8("layoutAuthCfg"))
        self.editAuthCfg = QtGui.QLineEdit(QgsPluginInstallerRepositoryDetailsDialogBase)
        self.editAuthCfg.setReadOnly(True)
        self.editAuthCfg.setObjectName(_fromUtf8("editAuthCfg"))
        self.layoutAuthCfg.addWidget(self.editAuthCfg)
        self.btnClearAuthCfg = QtGui.QToolButton(QgsPluginInstallerRepositoryDetailsDialogBase)
        self.btnClearAuthCfg.setMaximumSize(QtCore.QSize(16777215, 22))
        self.btnClearAuthCfg.setObjectName(_fromUtf8("btnClearAuthCfg"))
        self.layoutAuthCfg.addWidget(self.btnClearAuthCfg)
        self.btnEditAuthCfg = QtGui.QToolButton(QgsPluginInstallerRepositoryDetailsDialogBase)
        self.btnEditAuthCfg.setMaximumSize(QtCore.QSize(16777215, 22))
        self.btnEditAuthCfg.setObjectName(_fromUtf8("btnEditAuthCfg"))
        self.layoutAuthCfg.addWidget(self.btnEditAuthCfg)
        self.gridlayout.addLayout(self.layoutAuthCfg, 4, 1, 1, 2)
        self.label_2.setBuddy(self.editURL)
        self.label_4.setBuddy(self.checkBoxEnabled)
        self.label.setBuddy(self.editName)
        self.label_3.setBuddy(self.editParams)

        self.retranslateUi(QgsPluginInstallerRepositoryDetailsDialogBase)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), QgsPluginInstallerRepositoryDetailsDialogBase.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), QgsPluginInstallerRepositoryDetailsDialogBase.reject)
        QtCore.QMetaObject.connectSlotsByName(QgsPluginInstallerRepositoryDetailsDialogBase)
        QgsPluginInstallerRepositoryDetailsDialogBase.setTabOrder(self.editName, self.editURL)
        QgsPluginInstallerRepositoryDetailsDialogBase.setTabOrder(self.editURL, self.editParams)
        QgsPluginInstallerRepositoryDetailsDialogBase.setTabOrder(self.editParams, self.checkBoxEnabled)
        QgsPluginInstallerRepositoryDetailsDialogBase.setTabOrder(self.checkBoxEnabled, self.buttonBox)

    def retranslateUi(self, QgsPluginInstallerRepositoryDetailsDialogBase):
        QgsPluginInstallerRepositoryDetailsDialogBase.setWindowTitle(_translate("QgsPluginInstallerRepositoryDetailsDialogBase", "Repository details", None))
        self.label_2.setText(_translate("QgsPluginInstallerRepositoryDetailsDialogBase", "URL", None))
        self.label_4.setText(_translate("QgsPluginInstallerRepositoryDetailsDialogBase", "Enabled", None))
        self.editName.setToolTip(_translate("QgsPluginInstallerRepositoryDetailsDialogBase", "Enter a name for the repository", None))
        self.editName.setWhatsThis(_translate("QgsPluginInstallerRepositoryDetailsDialogBase", "Enter a name for the repository", None))
        self.editParams.setText(_translate("QgsPluginInstallerRepositoryDetailsDialogBase", "?qgis=", None))
        self.label.setText(_translate("QgsPluginInstallerRepositoryDetailsDialogBase", "Name", None))
        self.label_3.setText(_translate("QgsPluginInstallerRepositoryDetailsDialogBase", "Parameters", None))
        self.checkBoxEnabled.setToolTip(_translate("QgsPluginInstallerRepositoryDetailsDialogBase", "Enable or disable the repository (disabled repositories will be omitted)", None))
        self.checkBoxEnabled.setWhatsThis(_translate("QgsPluginInstallerRepositoryDetailsDialogBase", "Enable or disable the repository (disabled repositories will be omitted)", None))
        self.editURL.setToolTip(_translate("QgsPluginInstallerRepositoryDetailsDialogBase", "Enter the repository URL, beginning with \"http://\"", None))
        self.editURL.setWhatsThis(_translate("QgsPluginInstallerRepositoryDetailsDialogBase", "Enter the repository URL, beginning with \"http://\"", None))
        self.label_5.setText(_translate("QgsPluginInstallerRepositoryDetailsDialogBase", "Authentication", None))
        self.btnClearAuthCfg.setText(_translate("QgsPluginInstallerRepositoryDetailsDialogBase", "Clear", None))
        self.btnEditAuthCfg.setText(_translate("QgsPluginInstallerRepositoryDetailsDialogBase", "Edit", None))

