# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/src/qgis/python/plugins/db_manager/ui/DlgImportVector.ui'
#
# Created: Sat Aug 18 08:04:40 2018
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DbManagerDlgImportVector(object):
    def setupUi(self, DbManagerDlgImportVector):
        DbManagerDlgImportVector.setObjectName(_fromUtf8("DbManagerDlgImportVector"))
        DbManagerDlgImportVector.resize(482, 496)
        self.verticalLayout = QtGui.QVBoxLayout(DbManagerDlgImportVector)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.wdgInput = QtGui.QWidget(DbManagerDlgImportVector)
        self.wdgInput.setObjectName(_fromUtf8("wdgInput"))
        self.gridLayout_3 = QtGui.QGridLayout(self.wdgInput)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_5 = QtGui.QLabel(self.wdgInput)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.btnChooseInputFile = QtGui.QToolButton(self.wdgInput)
        self.btnChooseInputFile.setObjectName(_fromUtf8("btnChooseInputFile"))
        self.gridLayout_3.addWidget(self.btnChooseInputFile, 0, 3, 1, 1)
        self.line = QtGui.QFrame(self.wdgInput)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_3.addWidget(self.line, 2, 0, 1, 4)
        self.cboInputLayer = QtGui.QComboBox(self.wdgInput)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboInputLayer.sizePolicy().hasHeightForWidth())
        self.cboInputLayer.setSizePolicy(sizePolicy)
        self.cboInputLayer.setEditable(True)
        self.cboInputLayer.setInsertPolicy(QtGui.QComboBox.NoInsert)
        self.cboInputLayer.setObjectName(_fromUtf8("cboInputLayer"))
        self.gridLayout_3.addWidget(self.cboInputLayer, 0, 1, 1, 2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.chkSelectedFeatures = QtGui.QCheckBox(self.wdgInput)
        self.chkSelectedFeatures.setObjectName(_fromUtf8("chkSelectedFeatures"))
        self.horizontalLayout_2.addWidget(self.chkSelectedFeatures)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btnUpdateInputLayer = QtGui.QPushButton(self.wdgInput)
        self.btnUpdateInputLayer.setObjectName(_fromUtf8("btnUpdateInputLayer"))
        self.horizontalLayout_2.addWidget(self.btnUpdateInputLayer)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 1, 0, 1, 4)
        self.verticalLayout.addWidget(self.wdgInput)
        self.groupBox_3 = QtGui.QGroupBox(DbManagerDlgImportVector)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_2 = QtGui.QLabel(self.groupBox_3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.cboSchema = QtGui.QComboBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboSchema.sizePolicy().hasHeightForWidth())
        self.cboSchema.setSizePolicy(sizePolicy)
        self.cboSchema.setObjectName(_fromUtf8("cboSchema"))
        self.gridLayout_2.addWidget(self.cboSchema, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox_3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.cboTable = QtGui.QComboBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboTable.sizePolicy().hasHeightForWidth())
        self.cboTable.setSizePolicy(sizePolicy)
        self.cboTable.setEditable(True)
        self.cboTable.setInsertPolicy(QtGui.QComboBox.NoInsert)
        self.cboTable.setObjectName(_fromUtf8("cboTable"))
        self.gridLayout_2.addWidget(self.cboTable, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_2 = QtGui.QGroupBox(DbManagerDlgImportVector)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.chkPrimaryKey = QtGui.QCheckBox(self.groupBox_2)
        self.chkPrimaryKey.setObjectName(_fromUtf8("chkPrimaryKey"))
        self.gridLayout.addWidget(self.chkPrimaryKey, 0, 0, 1, 1)
        self.editPrimaryKey = QtGui.QLineEdit(self.groupBox_2)
        self.editPrimaryKey.setEnabled(False)
        self.editPrimaryKey.setObjectName(_fromUtf8("editPrimaryKey"))
        self.gridLayout.addWidget(self.editPrimaryKey, 0, 1, 1, 1)
        self.chkGeomColumn = QtGui.QCheckBox(self.groupBox_2)
        self.chkGeomColumn.setObjectName(_fromUtf8("chkGeomColumn"))
        self.gridLayout.addWidget(self.chkGeomColumn, 1, 0, 1, 1)
        self.editGeomColumn = QtGui.QLineEdit(self.groupBox_2)
        self.editGeomColumn.setEnabled(False)
        self.editGeomColumn.setObjectName(_fromUtf8("editGeomColumn"))
        self.gridLayout.addWidget(self.editGeomColumn, 1, 1, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.chkSourceSrid = QtGui.QCheckBox(self.groupBox_2)
        self.chkSourceSrid.setObjectName(_fromUtf8("chkSourceSrid"))
        self.horizontalLayout.addWidget(self.chkSourceSrid)
        self.editSourceSrid = QtGui.QLineEdit(self.groupBox_2)
        self.editSourceSrid.setEnabled(False)
        self.editSourceSrid.setObjectName(_fromUtf8("editSourceSrid"))
        self.horizontalLayout.addWidget(self.editSourceSrid)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.chkTargetSrid = QtGui.QCheckBox(self.groupBox_2)
        self.chkTargetSrid.setObjectName(_fromUtf8("chkTargetSrid"))
        self.horizontalLayout.addWidget(self.chkTargetSrid)
        self.editTargetSrid = QtGui.QLineEdit(self.groupBox_2)
        self.editTargetSrid.setEnabled(False)
        self.editTargetSrid.setObjectName(_fromUtf8("editTargetSrid"))
        self.horizontalLayout.addWidget(self.editTargetSrid)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 2)
        self.chkEncoding = QtGui.QCheckBox(self.groupBox_2)
        self.chkEncoding.setObjectName(_fromUtf8("chkEncoding"))
        self.gridLayout.addWidget(self.chkEncoding, 3, 0, 1, 1)
        self.cboEncoding = QtGui.QComboBox(self.groupBox_2)
        self.cboEncoding.setEnabled(False)
        self.cboEncoding.setEditable(True)
        self.cboEncoding.setObjectName(_fromUtf8("cboEncoding"))
        self.gridLayout.addWidget(self.cboEncoding, 3, 1, 1, 1)
        self.chkSinglePart = QtGui.QCheckBox(self.groupBox_2)
        self.chkSinglePart.setObjectName(_fromUtf8("chkSinglePart"))
        self.gridLayout.addWidget(self.chkSinglePart, 6, 0, 1, 2)
        self.chkSpatialIndex = QtGui.QCheckBox(self.groupBox_2)
        self.chkSpatialIndex.setObjectName(_fromUtf8("chkSpatialIndex"))
        self.gridLayout.addWidget(self.chkSpatialIndex, 8, 0, 1, 2)
        self.chkDropTable = QtGui.QCheckBox(self.groupBox_2)
        self.chkDropTable.setObjectName(_fromUtf8("chkDropTable"))
        self.gridLayout.addWidget(self.chkDropTable, 4, 0, 1, 2)
        self.chkLowercaseFieldNames = QtGui.QCheckBox(self.groupBox_2)
        self.chkLowercaseFieldNames.setObjectName(_fromUtf8("chkLowercaseFieldNames"))
        self.gridLayout.addWidget(self.chkLowercaseFieldNames, 7, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.buttonBox = QtGui.QDialogButtonBox(DbManagerDlgImportVector)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(DbManagerDlgImportVector)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), DbManagerDlgImportVector.reject)
        QtCore.QObject.connect(self.chkPrimaryKey, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.editPrimaryKey.setEnabled)
        QtCore.QObject.connect(self.chkGeomColumn, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.editGeomColumn.setEnabled)
        QtCore.QObject.connect(self.chkSourceSrid, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.editSourceSrid.setEnabled)
        QtCore.QObject.connect(self.chkTargetSrid, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.editTargetSrid.setEnabled)
        QtCore.QObject.connect(self.chkEncoding, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cboEncoding.setEnabled)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), DbManagerDlgImportVector.accept)
        QtCore.QMetaObject.connectSlotsByName(DbManagerDlgImportVector)
        DbManagerDlgImportVector.setTabOrder(self.chkSourceSrid, self.editSourceSrid)
        DbManagerDlgImportVector.setTabOrder(self.editSourceSrid, self.chkEncoding)
        DbManagerDlgImportVector.setTabOrder(self.chkEncoding, self.cboEncoding)
        DbManagerDlgImportVector.setTabOrder(self.cboEncoding, self.chkSinglePart)
        DbManagerDlgImportVector.setTabOrder(self.chkSinglePart, self.chkSpatialIndex)
        DbManagerDlgImportVector.setTabOrder(self.chkSpatialIndex, self.buttonBox)

    def retranslateUi(self, DbManagerDlgImportVector):
        DbManagerDlgImportVector.setWindowTitle(_translate("DbManagerDlgImportVector", "Import vector layer", None))
        self.label_5.setText(_translate("DbManagerDlgImportVector", "Input", None))
        self.btnChooseInputFile.setText(_translate("DbManagerDlgImportVector", "...", None))
        self.chkSelectedFeatures.setText(_translate("DbManagerDlgImportVector", "Import only selected features", None))
        self.btnUpdateInputLayer.setText(_translate("DbManagerDlgImportVector", "Update options", None))
        self.groupBox_3.setTitle(_translate("DbManagerDlgImportVector", "Output table", None))
        self.label_2.setText(_translate("DbManagerDlgImportVector", "Schema", None))
        self.label_3.setText(_translate("DbManagerDlgImportVector", "Table", None))
        self.groupBox_2.setTitle(_translate("DbManagerDlgImportVector", "Options", None))
        self.chkPrimaryKey.setText(_translate("DbManagerDlgImportVector", "Primary key", None))
        self.chkGeomColumn.setText(_translate("DbManagerDlgImportVector", "Geometry column", None))
        self.chkSourceSrid.setText(_translate("DbManagerDlgImportVector", "Source SRID", None))
        self.chkTargetSrid.setText(_translate("DbManagerDlgImportVector", "Target SRID", None))
        self.chkEncoding.setText(_translate("DbManagerDlgImportVector", "Encoding", None))
        self.chkSinglePart.setText(_translate("DbManagerDlgImportVector", "Create single-part geometries instead of multi-part", None))
        self.chkSpatialIndex.setText(_translate("DbManagerDlgImportVector", "Create spatial index", None))
        self.chkDropTable.setText(_translate("DbManagerDlgImportVector", "Replace destination table (if exists)", None))
        self.chkLowercaseFieldNames.setText(_translate("DbManagerDlgImportVector", "Convert field names to lowercase", None))

