# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/src/qgis/python/plugins/GdalTools/tools/widgetRasterize.ui'
#
# Created: Sat Aug 18 08:04:35 2018
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_GdalToolsWidget(object):
    def setupUi(self, GdalToolsWidget):
        GdalToolsWidget.setObjectName(_fromUtf8("GdalToolsWidget"))
        GdalToolsWidget.resize(509, 261)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(GdalToolsWidget.sizePolicy().hasHeightForWidth())
        GdalToolsWidget.setSizePolicy(sizePolicy)
        self.verticalLayout = QtGui.QVBoxLayout(GdalToolsWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label = QtGui.QLabel(GdalToolsWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(GdalToolsWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.attributeComboBox = QtGui.QComboBox(GdalToolsWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.attributeComboBox.sizePolicy().hasHeightForWidth())
        self.attributeComboBox.setSizePolicy(sizePolicy)
        self.attributeComboBox.setObjectName(_fromUtf8("attributeComboBox"))
        self.gridLayout_2.addWidget(self.attributeComboBox, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(GdalToolsWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1)
        self.inSelector = GdalToolsInOutSelector(GdalToolsWidget)
        self.inSelector.setObjectName(_fromUtf8("inSelector"))
        self.gridLayout_2.addWidget(self.inSelector, 0, 1, 1, 1)
        self.outSelector = GdalToolsInOutSelector(GdalToolsWidget)
        self.outSelector.setObjectName(_fromUtf8("outSelector"))
        self.gridLayout_2.addWidget(self.outSelector, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.radioKeepSize = QtGui.QRadioButton(GdalToolsWidget)
        self.radioKeepSize.setChecked(True)
        self.radioKeepSize.setObjectName(_fromUtf8("radioKeepSize"))
        self.verticalLayout.addWidget(self.radioKeepSize)
        self.radioSetSize = QtGui.QRadioButton(GdalToolsWidget)
        self.radioSetSize.setChecked(False)
        self.radioSetSize.setObjectName(_fromUtf8("radioSetSize"))
        self.verticalLayout.addWidget(self.radioSetSize)
        self.widgetSize = QtGui.QWidget(GdalToolsWidget)
        self.widgetSize.setEnabled(False)
        self.widgetSize.setObjectName(_fromUtf8("widgetSize"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widgetSize)
        self.horizontalLayout.setContentsMargins(30, 0, 0, -1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.labelWidth = QtGui.QLabel(self.widgetSize)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelWidth.sizePolicy().hasHeightForWidth())
        self.labelWidth.setSizePolicy(sizePolicy)
        self.labelWidth.setObjectName(_fromUtf8("labelWidth"))
        self.horizontalLayout.addWidget(self.labelWidth)
        self.widthSpin = QtGui.QSpinBox(self.widgetSize)
        self.widthSpin.setMaximum(999999)
        self.widthSpin.setObjectName(_fromUtf8("widthSpin"))
        self.horizontalLayout.addWidget(self.widthSpin)
        self.labelHeight = QtGui.QLabel(self.widgetSize)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelHeight.sizePolicy().hasHeightForWidth())
        self.labelHeight.setSizePolicy(sizePolicy)
        self.labelHeight.setIndent(40)
        self.labelHeight.setObjectName(_fromUtf8("labelHeight"))
        self.horizontalLayout.addWidget(self.labelHeight)
        self.heightSpin = QtGui.QSpinBox(self.widgetSize)
        self.heightSpin.setMaximum(999999)
        self.heightSpin.setObjectName(_fromUtf8("heightSpin"))
        self.horizontalLayout.addWidget(self.heightSpin)
        self.verticalLayout.addWidget(self.widgetSize)
        self.radioSetResolution = QtGui.QRadioButton(GdalToolsWidget)
        self.radioSetResolution.setObjectName(_fromUtf8("radioSetResolution"))
        self.verticalLayout.addWidget(self.radioSetResolution)
        self.widgetResolution = QtGui.QWidget(GdalToolsWidget)
        self.widgetResolution.setEnabled(False)
        self.widgetResolution.setObjectName(_fromUtf8("widgetResolution"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widgetResolution)
        self.horizontalLayout_2.setContentsMargins(30, 0, 0, -1)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.labelHorizontal = QtGui.QLabel(self.widgetResolution)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelHorizontal.sizePolicy().hasHeightForWidth())
        self.labelHorizontal.setSizePolicy(sizePolicy)
        self.labelHorizontal.setObjectName(_fromUtf8("labelHorizontal"))
        self.horizontalLayout_2.addWidget(self.labelHorizontal)
        self.horizresSpin = QtGui.QDoubleSpinBox(self.widgetResolution)
        self.horizresSpin.setDecimals(8)
        self.horizresSpin.setMaximum(999999999.99)
        self.horizresSpin.setProperty("value", 1.0)
        self.horizresSpin.setObjectName(_fromUtf8("horizresSpin"))
        self.horizontalLayout_2.addWidget(self.horizresSpin)
        self.labelVertical = QtGui.QLabel(self.widgetResolution)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelVertical.sizePolicy().hasHeightForWidth())
        self.labelVertical.setSizePolicy(sizePolicy)
        self.labelVertical.setIndent(40)
        self.labelVertical.setObjectName(_fromUtf8("labelVertical"))
        self.horizontalLayout_2.addWidget(self.labelVertical)
        self.vertresSpin = QtGui.QDoubleSpinBox(self.widgetResolution)
        self.vertresSpin.setInputMethodHints(QtCore.Qt.ImhNone)
        self.vertresSpin.setDecimals(8)
        self.vertresSpin.setMaximum(999999999.99)
        self.vertresSpin.setSingleStep(1.0)
        self.vertresSpin.setProperty("value", 2.0)
        self.vertresSpin.setObjectName(_fromUtf8("vertresSpin"))
        self.horizontalLayout_2.addWidget(self.vertresSpin)
        self.verticalLayout.addWidget(self.widgetResolution)
        self.label.setBuddy(self.inSelector)
        self.label_3.setBuddy(self.attributeComboBox)
        self.label_2.setBuddy(self.outSelector)

        self.retranslateUi(GdalToolsWidget)
        QtCore.QObject.connect(self.radioSetSize, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.widgetSize.setEnabled)
        QtCore.QObject.connect(self.radioSetResolution, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.widgetResolution.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(GdalToolsWidget)

    def retranslateUi(self, GdalToolsWidget):
        GdalToolsWidget.setWindowTitle(_translate("GdalToolsWidget", "Rasterize (Vector to raster)", None))
        self.label.setText(_translate("GdalToolsWidget", "&Input file (shapefile)", None))
        self.label_3.setText(_translate("GdalToolsWidget", "&Attribute field", None))
        self.label_2.setText(_translate("GdalToolsWidget", "&Output file for rasterized vectors (raster)", None))
        self.radioKeepSize.setText(_translate("GdalToolsWidget", "Keep existing raster size and resolution", None))
        self.radioSetSize.setText(_translate("GdalToolsWidget", "Raster size in pixels", None))
        self.labelWidth.setText(_translate("GdalToolsWidget", "Width", None))
        self.labelHeight.setText(_translate("GdalToolsWidget", "Height", None))
        self.radioSetResolution.setText(_translate("GdalToolsWidget", "Raster resolution in map units per pixel", None))
        self.labelHorizontal.setText(_translate("GdalToolsWidget", "Horizontal", None))
        self.labelVertical.setText(_translate("GdalToolsWidget", "Vertical", None))

from .inOutSelector import GdalToolsInOutSelector
