# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/src/qgis/python/plugins/GdalTools/tools/widgetDEM.ui'
#
# Created: Sat Aug 18 08:04:33 2018
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_GdalToolsWidget(object):
    def setupUi(self, GdalToolsWidget):
        GdalToolsWidget.setObjectName(_fromUtf8("GdalToolsWidget"))
        GdalToolsWidget.resize(478, 404)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(GdalToolsWidget.sizePolicy().hasHeightForWidth())
        GdalToolsWidget.setSizePolicy(sizePolicy)
        self.verticalLayout_2 = QtGui.QVBoxLayout(GdalToolsWidget)
        self.verticalLayout_2.setContentsMargins(5, -1, -1, -1)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(GdalToolsWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(GdalToolsWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.bandCheck = QtGui.QCheckBox(GdalToolsWidget)
        self.bandCheck.setObjectName(_fromUtf8("bandCheck"))
        self.gridLayout.addWidget(self.bandCheck, 2, 0, 1, 1)
        self.bandSpin = QtGui.QSpinBox(GdalToolsWidget)
        self.bandSpin.setMinimum(1)
        self.bandSpin.setObjectName(_fromUtf8("bandSpin"))
        self.gridLayout.addWidget(self.bandSpin, 2, 1, 1, 1)
        self.computeEdgesCheck = QtGui.QCheckBox(GdalToolsWidget)
        self.computeEdgesCheck.setObjectName(_fromUtf8("computeEdgesCheck"))
        self.gridLayout.addWidget(self.computeEdgesCheck, 3, 0, 1, 2)
        self.algorithmCheck = QtGui.QCheckBox(GdalToolsWidget)
        self.algorithmCheck.setObjectName(_fromUtf8("algorithmCheck"))
        self.gridLayout.addWidget(self.algorithmCheck, 4, 0, 1, 2)
        self.inSelector = GdalToolsInOutSelector(GdalToolsWidget)
        self.inSelector.setObjectName(_fromUtf8("inSelector"))
        self.gridLayout.addWidget(self.inSelector, 0, 1, 1, 1)
        self.outSelector = GdalToolsInOutSelector(GdalToolsWidget)
        self.outSelector.setObjectName(_fromUtf8("outSelector"))
        self.gridLayout.addWidget(self.outSelector, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(GdalToolsWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 5, 0, 1, 1)
        self.modeCombo = QtGui.QComboBox(GdalToolsWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modeCombo.sizePolicy().hasHeightForWidth())
        self.modeCombo.setSizePolicy(sizePolicy)
        self.modeCombo.setObjectName(_fromUtf8("modeCombo"))
        self.modeCombo.addItem(_fromUtf8(""))
        self.modeCombo.addItem(_fromUtf8(""))
        self.modeCombo.addItem(_fromUtf8(""))
        self.modeCombo.addItem(_fromUtf8(""))
        self.modeCombo.addItem(_fromUtf8(""))
        self.modeCombo.addItem(_fromUtf8(""))
        self.modeCombo.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.modeCombo, 5, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.groupBox = QtGui.QGroupBox(GdalToolsWidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.stackedWidget = QtGui.QStackedWidget(self.groupBox)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.gridLayout_3 = QtGui.QGridLayout(self.page)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_4 = QtGui.QLabel(self.page)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.hillshadeZFactorSpin = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hillshadeZFactorSpin.sizePolicy().hasHeightForWidth())
        self.hillshadeZFactorSpin.setSizePolicy(sizePolicy)
        self.hillshadeZFactorSpin.setDecimals(2)
        self.hillshadeZFactorSpin.setMaximum(100000000.0)
        self.hillshadeZFactorSpin.setObjectName(_fromUtf8("hillshadeZFactorSpin"))
        self.gridLayout_3.addWidget(self.hillshadeZFactorSpin, 0, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.page)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 1, 0, 1, 1)
        self.hillshadeScaleSpin = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hillshadeScaleSpin.sizePolicy().hasHeightForWidth())
        self.hillshadeScaleSpin.setSizePolicy(sizePolicy)
        self.hillshadeScaleSpin.setDecimals(2)
        self.hillshadeScaleSpin.setMaximum(999999.0)
        self.hillshadeScaleSpin.setObjectName(_fromUtf8("hillshadeScaleSpin"))
        self.gridLayout_3.addWidget(self.hillshadeScaleSpin, 1, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.page)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 2, 0, 1, 1)
        self.hillshadeAzimuthSpin = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hillshadeAzimuthSpin.sizePolicy().hasHeightForWidth())
        self.hillshadeAzimuthSpin.setSizePolicy(sizePolicy)
        self.hillshadeAzimuthSpin.setDecimals(1)
        self.hillshadeAzimuthSpin.setMaximum(359.0)
        self.hillshadeAzimuthSpin.setObjectName(_fromUtf8("hillshadeAzimuthSpin"))
        self.gridLayout_3.addWidget(self.hillshadeAzimuthSpin, 2, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.page)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 3, 0, 1, 1)
        self.hillshadeAltitudeSpin = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hillshadeAltitudeSpin.sizePolicy().hasHeightForWidth())
        self.hillshadeAltitudeSpin.setSizePolicy(sizePolicy)
        self.hillshadeAltitudeSpin.setDecimals(1)
        self.hillshadeAltitudeSpin.setMaximum(359.0)
        self.hillshadeAltitudeSpin.setObjectName(_fromUtf8("hillshadeAltitudeSpin"))
        self.gridLayout_3.addWidget(self.hillshadeAltitudeSpin, 3, 1, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.page_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.slopePercentCheck = QtGui.QCheckBox(self.page_2)
        self.slopePercentCheck.setObjectName(_fromUtf8("slopePercentCheck"))
        self.gridLayout_2.addWidget(self.slopePercentCheck, 0, 0, 1, 2)
        self.label_8 = QtGui.QLabel(self.page_2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 1, 0, 1, 1)
        self.slopeScaleSpin = QtGui.QDoubleSpinBox(self.page_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slopeScaleSpin.sizePolicy().hasHeightForWidth())
        self.slopeScaleSpin.setSizePolicy(sizePolicy)
        self.slopeScaleSpin.setDecimals(2)
        self.slopeScaleSpin.setMaximum(999999.0)
        self.slopeScaleSpin.setObjectName(_fromUtf8("slopeScaleSpin"))
        self.gridLayout_2.addWidget(self.slopeScaleSpin, 1, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 2, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.gridLayout_4 = QtGui.QGridLayout(self.page_3)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.aspectTrigonometricCheck = QtGui.QCheckBox(self.page_3)
        self.aspectTrigonometricCheck.setObjectName(_fromUtf8("aspectTrigonometricCheck"))
        self.gridLayout_4.addWidget(self.aspectTrigonometricCheck, 0, 0, 1, 1)
        self.aspectZeroForFlatCheck = QtGui.QCheckBox(self.page_3)
        self.aspectZeroForFlatCheck.setObjectName(_fromUtf8("aspectZeroForFlatCheck"))
        self.gridLayout_4.addWidget(self.aspectZeroForFlatCheck, 1, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem1, 2, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtGui.QWidget()
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.gridLayout_5 = QtGui.QGridLayout(self.page_4)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_9 = QtGui.QLabel(self.page_4)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_5.addWidget(self.label_9, 0, 0, 1, 1)
        self.colorMatchGroupBox = QtGui.QGroupBox(self.page_4)
        self.colorMatchGroupBox.setCheckable(True)
        self.colorMatchGroupBox.setChecked(False)
        self.colorMatchGroupBox.setObjectName(_fromUtf8("colorMatchGroupBox"))
        self.gridLayout_6 = QtGui.QGridLayout(self.colorMatchGroupBox)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.colorExactRadio = QtGui.QRadioButton(self.colorMatchGroupBox)
        self.colorExactRadio.setCheckable(True)
        self.colorExactRadio.setChecked(True)
        self.colorExactRadio.setObjectName(_fromUtf8("colorExactRadio"))
        self.gridLayout_6.addWidget(self.colorExactRadio, 0, 0, 1, 1)
        self.colorNearestRadio = QtGui.QRadioButton(self.colorMatchGroupBox)
        self.colorNearestRadio.setObjectName(_fromUtf8("colorNearestRadio"))
        self.gridLayout_6.addWidget(self.colorNearestRadio, 1, 0, 1, 1)
        self.gridLayout_5.addWidget(self.colorMatchGroupBox, 1, 0, 1, 2)
        self.colorAlphaCheck = QtGui.QCheckBox(self.page_4)
        self.colorAlphaCheck.setObjectName(_fromUtf8("colorAlphaCheck"))
        self.gridLayout_5.addWidget(self.colorAlphaCheck, 2, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem2, 3, 0, 1, 1)
        self.configSelector = GdalToolsInOutSelector(self.page_4)
        self.configSelector.setObjectName(_fromUtf8("configSelector"))
        self.gridLayout_5.addWidget(self.configSelector, 0, 1, 1, 1)
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtGui.QWidget()
        self.page_5.setObjectName(_fromUtf8("page_5"))
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtGui.QWidget()
        self.page_6.setObjectName(_fromUtf8("page_6"))
        self.stackedWidget.addWidget(self.page_6)
        self.page_7 = QtGui.QWidget()
        self.page_7.setObjectName(_fromUtf8("page_7"))
        self.stackedWidget.addWidget(self.page_7)
        self.verticalLayout_3.addWidget(self.stackedWidget)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.creationOptionsGroupBox = QgsCollapsibleGroupBox(GdalToolsWidget)
        self.creationOptionsGroupBox.setProperty("collapsed", False)
        self.creationOptionsGroupBox.setProperty("saveCollapsedState", True)
        self.creationOptionsGroupBox.setEnabled(True)
        self.creationOptionsGroupBox.setCheckable(True)
        self.creationOptionsGroupBox.setChecked(False)
        self.creationOptionsGroupBox.setObjectName(_fromUtf8("creationOptionsGroupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.creationOptionsGroupBox)
        self.verticalLayout.setContentsMargins(9, -1, -1, -1)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.creationOptionsWidget = QgsRasterFormatSaveOptionsWidget(self.creationOptionsGroupBox)
        self.creationOptionsWidget.setObjectName(_fromUtf8("creationOptionsWidget"))
        self.verticalLayout.addWidget(self.creationOptionsWidget)
        self.verticalLayout_2.addWidget(self.creationOptionsGroupBox)
        self.label.setBuddy(self.inSelector)
        self.label_2.setBuddy(self.outSelector)
        self.label_3.setBuddy(self.modeCombo)

        self.retranslateUi(GdalToolsWidget)
        self.modeCombo.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.modeCombo, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.stackedWidget.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(GdalToolsWidget)

    def retranslateUi(self, GdalToolsWidget):
        GdalToolsWidget.setWindowTitle(_translate("GdalToolsWidget", "DEM (Terrain models)", None))
        self.label.setText(_translate("GdalToolsWidget", "&Input file (DEM raster)", None))
        self.label_2.setText(_translate("GdalToolsWidget", "&Output file", None))
        self.bandCheck.setText(_translate("GdalToolsWidget", "&Band", None))
        self.computeEdgesCheck.setText(_translate("GdalToolsWidget", "Compute &edges", None))
        self.algorithmCheck.setText(_translate("GdalToolsWidget", "Use Zevenbergen&&Thorne formula (instead of the Horn\'s one)", None))
        self.label_3.setText(_translate("GdalToolsWidget", "&Mode", None))
        self.modeCombo.setItemText(0, _translate("GdalToolsWidget", "Hillshade", None))
        self.modeCombo.setItemText(1, _translate("GdalToolsWidget", "Slope", None))
        self.modeCombo.setItemText(2, _translate("GdalToolsWidget", "Aspect", None))
        self.modeCombo.setItemText(3, _translate("GdalToolsWidget", "Color relief", None))
        self.modeCombo.setItemText(4, _translate("GdalToolsWidget", "TRI (Terrain Ruggedness Index)", None))
        self.modeCombo.setItemText(5, _translate("GdalToolsWidget", "TPI (Topographic Position Index)", None))
        self.modeCombo.setItemText(6, _translate("GdalToolsWidget", "Roughness", None))
        self.groupBox.setTitle(_translate("GdalToolsWidget", "Mode Options", None))
        self.label_4.setText(_translate("GdalToolsWidget", "Z factor (vertical exaggeration)", None))
        self.label_5.setText(_translate("GdalToolsWidget", "Scale (ratio of vert. units to horiz.)", None))
        self.label_6.setText(_translate("GdalToolsWidget", "Azimuth of the light", None))
        self.label_7.setText(_translate("GdalToolsWidget", "Altitude of the light", None))
        self.slopePercentCheck.setText(_translate("GdalToolsWidget", "Slope expressed as percent (instead of as degrees)", None))
        self.label_8.setText(_translate("GdalToolsWidget", "Scale (ratio of vert. units to horiz.)", None))
        self.aspectTrigonometricCheck.setText(_translate("GdalToolsWidget", "Return trigonometric angle (instead of azimuth)", None))
        self.aspectZeroForFlatCheck.setText(_translate("GdalToolsWidget", "Return 0 for flat (instead of -9999)", None))
        self.label_9.setText(_translate("GdalToolsWidget", "Color configuration file", None))
        self.colorMatchGroupBox.setTitle(_translate("GdalToolsWidget", "Matching mode", None))
        self.colorExactRadio.setText(_translate("GdalToolsWidget", "Exact color (otherwise \"0,0,0,0\" RGBA)", None))
        self.colorNearestRadio.setText(_translate("GdalToolsWidget", "Nearest color", None))
        self.colorAlphaCheck.setText(_translate("GdalToolsWidget", "Add alpha channel", None))
        self.creationOptionsGroupBox.setTitle(_translate("GdalToolsWidget", "&Creation Options", None))

from qgis.gui import QgsCollapsibleGroupBox, QgsRasterFormatSaveOptionsWidget
from .inOutSelector import GdalToolsInOutSelector
