.TH g.gui.tplot 1 "" "GRASS 7.4.1" "Grass User's Manual"
.SH NAME
\fI\fBg.gui.tplot\fR\fR  \- Plots the values of temporal datasets.
.SH KEYWORDS
general, GUI, temporal
.SH SYNOPSIS
\fBg.gui.tplot\fR
.br
\fBg.gui.tplot \-\-help\fR
.br
\fBg.gui.tplot\fR  [\fBstvds\fR=\fIname\fR[,\fIname\fR,...]]   [\fBstrds\fR=\fIname\fR[,\fIname\fR,...]]   [\fBcoordinates\fR=\fIeast,north\fR]   [\fBcats\fR=\fIstring\fR]   [\fBattr\fR=\fIstring\fR]   [\fBoutput\fR=\fIname\fR]   [\fBsize\fR=\fIstring\fR]   [\-\-\fBoverwrite\fR]  [\-\-\fBhelp\fR]  [\-\-\fBverbose\fR]  [\-\-\fBquiet\fR]  [\-\-\fBui\fR]
.SS Flags:
.IP "\fB\-\-overwrite\fR" 4m
.br
Allow output files to overwrite existing files
.IP "\fB\-\-help\fR" 4m
.br
Print usage summary
.IP "\fB\-\-verbose\fR" 4m
.br
Verbose module output
.IP "\fB\-\-quiet\fR" 4m
.br
Quiet module output
.IP "\fB\-\-ui\fR" 4m
.br
Force launching GUI dialog
.SS Parameters:
.IP "\fBstvds\fR=\fIname[,\fIname\fR,...]\fR" 4m
.br
Name of the input space time vector datasets
.IP "\fBstrds\fR=\fIname[,\fIname\fR,...]\fR" 4m
.br
Name of the input space time raster datasets
.IP "\fBcoordinates\fR=\fIeast,north\fR" 4m
.br
Coordinates
.IP "\fBcats\fR=\fIstring\fR" 4m
.br
Categories of vectores features
.br
To use only with stvds
.IP "\fBattr\fR=\fIstring\fR" 4m
.br
Name of attribute
.br
Name of attribute which represent data for plotting
.IP "\fBoutput\fR=\fIname\fR" 4m
.br
Name for output file
.br
Add extension to specify format (.png, .pdf, .svg)
.IP "\fBsize\fR=\fIstring\fR" 4m
.br
The size for output image
.br
It works only with output parameter
.SH DESCRIPTION
The \fBTemporal Plot Tool\fR is a \fIwxGUI\fR component
which allows the user to see in a plot the values of one or more temporal datasets (strds, stvds,
str3ds) for a queried point defined by a coordinate pair.
.PP
Supported features:
.RS 4n
.IP \(bu 4n
temporal datasets with interval/point and absolute/relative time,
.IP \(bu 4n
2D plots,
.IP \(bu 4n
pop\-up annotations with values information,
.IP \(bu 4n
automatic output to query several point.
.RE
.SH NOTES
\fIg.gui.tplot\fR requires the Python plotting library
Matplotlib.
.SH SEE ALSO
\fI
Temporal data processing
.br
wxGUI
.br
wxGUI components
\fR
.SH AUTHOR
Luca Delucchi,
Fondazione Edmund Mach, Italy
.PP
\fI$Date: 2014\-06\-26 15:50:20 +0200 (Thu, 26 Jun 2014) $\fR
.SH SOURCE CODE
.PP
Available at: wxGUI Temporal Plot Tool source code (history)
.PP
Main index |
GUI index |
Topics index |
Keywords index |
Graphical index |
Full index
.PP
© 2003\-2018
GRASS Development Team,
GRASS GIS 7.4.1 Reference Manual
