.TH grass-ogr 1 "" "GRASS 7.4.1" "Grass User's Manual"
.SH OGR DATABASE DRIVER
This driver is principally only used
by \fIv.external\fR.
.SH SEE ALSO
\fI
SQL support in GRASS GIS
\fI
\fR\fR
.PP
\fI
v.external
\fR
.PP
\fILast changed: $Date: 2014\-04\-20 12:28:15 +0200 (Sun, 20 Apr 2014) $\fR
.PP
Main index |
Topics index |
Keywords index |
Graphical index |
Full index
.PP
© 2003\-2018
GRASS Development Team,
GRASS GIS 7.4.1 Reference Manual
