.TH topic_groundwater_flow 1 "" "GRASS 7.4.1" "Grass User's Manual"
.SH Topic: groundwater flow
.TS
expand;
lw60 lw1 lw60.
T{
r.gwflow
T}	 	T{
Numerical calculation program for transient, confined and unconfined groundwater flow in two dimensions.
T}
.sp 1
T{
r3.gwflow
T}	 	T{
Numerical calculation program for transient, confined groundwater flow in three dimensions.
T}
.sp 1
.TE
.PP
\fISee also the corresponding keyword groundwater flow for additional references.\fR
.PP
Main index |
Topics index |
Keywords index |
Graphical index |
Full index
.PP
© 2003\-2018
GRASS Development Team,
GRASS GIS 7.4.1 Reference Manual
