# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/src/qgis/python/plugins/GdalTools/tools/dialogSettings.ui'
#
# Created: Sat Jun 23 08:09:31 2018
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_GdalToolsSettingsDialog(object):
    def setupUi(self, GdalToolsSettingsDialog):
        GdalToolsSettingsDialog.setObjectName(_fromUtf8("GdalToolsSettingsDialog"))
        GdalToolsSettingsDialog.resize(371, 341)
        self.verticalLayout = QtGui.QVBoxLayout(GdalToolsSettingsDialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label = QtGui.QLabel(GdalToolsSettingsDialog)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_6.addWidget(self.label)
        self.bin_tooltip_label = QtGui.QLabel(GdalToolsSettingsDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bin_tooltip_label.sizePolicy().hasHeightForWidth())
        self.bin_tooltip_label.setSizePolicy(sizePolicy)
        self.bin_tooltip_label.setText(_fromUtf8("##tooltip icon##"))
        self.bin_tooltip_label.setObjectName(_fromUtf8("bin_tooltip_label"))
        self.horizontalLayout_6.addWidget(self.bin_tooltip_label)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.leGdalBinPath = QtGui.QLineEdit(GdalToolsSettingsDialog)
        self.leGdalBinPath.setObjectName(_fromUtf8("leGdalBinPath"))
        self.horizontalLayout.addWidget(self.leGdalBinPath)
        self.btnSetBinPath = QtGui.QPushButton(GdalToolsSettingsDialog)
        self.btnSetBinPath.setObjectName(_fromUtf8("btnSetBinPath"))
        self.horizontalLayout.addWidget(self.btnSetBinPath)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_4 = QtGui.QLabel(GdalToolsSettingsDialog)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_8.addWidget(self.label_4)
        self.pymod_tooltip_label = QtGui.QLabel(GdalToolsSettingsDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pymod_tooltip_label.sizePolicy().hasHeightForWidth())
        self.pymod_tooltip_label.setSizePolicy(sizePolicy)
        self.pymod_tooltip_label.setText(_fromUtf8("##tooltip icon##"))
        self.pymod_tooltip_label.setObjectName(_fromUtf8("pymod_tooltip_label"))
        self.horizontalLayout_8.addWidget(self.pymod_tooltip_label)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.leGdalPymodPath = QtGui.QLineEdit(GdalToolsSettingsDialog)
        self.leGdalPymodPath.setObjectName(_fromUtf8("leGdalPymodPath"))
        self.horizontalLayout_4.addWidget(self.leGdalPymodPath)
        self.btnSetPymodPath = QtGui.QPushButton(GdalToolsSettingsDialog)
        self.btnSetPymodPath.setObjectName(_fromUtf8("btnSetPymodPath"))
        self.horizontalLayout_4.addWidget(self.btnSetPymodPath)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_5 = QtGui.QLabel(GdalToolsSettingsDialog)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_7.addWidget(self.label_5)
        self.help_tooltip_label = QtGui.QLabel(GdalToolsSettingsDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.help_tooltip_label.sizePolicy().hasHeightForWidth())
        self.help_tooltip_label.setSizePolicy(sizePolicy)
        self.help_tooltip_label.setText(_fromUtf8("##tooltip icon##"))
        self.help_tooltip_label.setObjectName(_fromUtf8("help_tooltip_label"))
        self.horizontalLayout_7.addWidget(self.help_tooltip_label)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.leGdalHelpPath = QtGui.QLineEdit(GdalToolsSettingsDialog)
        self.leGdalHelpPath.setObjectName(_fromUtf8("leGdalHelpPath"))
        self.horizontalLayout_5.addWidget(self.leGdalHelpPath)
        self.btnSetHelpPath = QtGui.QPushButton(GdalToolsSettingsDialog)
        self.btnSetHelpPath.setObjectName(_fromUtf8("btnSetHelpPath"))
        self.horizontalLayout_5.addWidget(self.btnSetHelpPath)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.label_2 = QtGui.QLabel(GdalToolsSettingsDialog)
        self.label_2.setEnabled(False)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.leGdalDataPath = QtGui.QLineEdit(GdalToolsSettingsDialog)
        self.leGdalDataPath.setEnabled(False)
        self.leGdalDataPath.setObjectName(_fromUtf8("leGdalDataPath"))
        self.horizontalLayout_2.addWidget(self.leGdalDataPath)
        self.btnSetDataPath = QtGui.QPushButton(GdalToolsSettingsDialog)
        self.btnSetDataPath.setEnabled(False)
        self.btnSetDataPath.setObjectName(_fromUtf8("btnSetDataPath"))
        self.horizontalLayout_2.addWidget(self.btnSetDataPath)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_3 = QtGui.QLabel(GdalToolsSettingsDialog)
        self.label_3.setEnabled(False)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.leGdalDriverPath = QtGui.QLineEdit(GdalToolsSettingsDialog)
        self.leGdalDriverPath.setEnabled(False)
        self.leGdalDriverPath.setObjectName(_fromUtf8("leGdalDriverPath"))
        self.horizontalLayout_3.addWidget(self.leGdalDriverPath)
        self.btnSetDriverPath = QtGui.QPushButton(GdalToolsSettingsDialog)
        self.btnSetDriverPath.setEnabled(False)
        self.btnSetDriverPath.setObjectName(_fromUtf8("btnSetDriverPath"))
        self.horizontalLayout_3.addWidget(self.btnSetDriverPath)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.buttonBox = QtGui.QDialogButtonBox(GdalToolsSettingsDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(GdalToolsSettingsDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), GdalToolsSettingsDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), GdalToolsSettingsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(GdalToolsSettingsDialog)

    def retranslateUi(self, GdalToolsSettingsDialog):
        GdalToolsSettingsDialog.setWindowTitle(_translate("GdalToolsSettingsDialog", "Gdal Tools settings", None))
        self.label.setText(_translate("GdalToolsSettingsDialog", "Path to the GDAL executables", None))
        self.btnSetBinPath.setText(_translate("GdalToolsSettingsDialog", "Browse", None))
        self.label_4.setText(_translate("GdalToolsSettingsDialog", "Path to the GDAL python modules", None))
        self.btnSetPymodPath.setText(_translate("GdalToolsSettingsDialog", "Browse", None))
        self.label_5.setText(_translate("GdalToolsSettingsDialog", "GDAL help path", None))
        self.btnSetHelpPath.setText(_translate("GdalToolsSettingsDialog", "Browse", None))
        self.label_2.setText(_translate("GdalToolsSettingsDialog", "GDAL data path", None))
        self.btnSetDataPath.setText(_translate("GdalToolsSettingsDialog", "Browse", None))
        self.label_3.setText(_translate("GdalToolsSettingsDialog", "GDAL driver path", None))
        self.btnSetDriverPath.setText(_translate("GdalToolsSettingsDialog", "Browse", None))

