# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/src/qgis/python/plugins/GdalTools/tools/widgetWarp.ui'
#
# Created: Sat Jun 23 08:09:35 2018
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_GdalToolsWidget(object):
    def setupUi(self, GdalToolsWidget):
        GdalToolsWidget.setObjectName(_fromUtf8("GdalToolsWidget"))
        GdalToolsWidget.resize(415, 422)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(GdalToolsWidget.sizePolicy().hasHeightForWidth())
        GdalToolsWidget.setSizePolicy(sizePolicy)
        self.gridLayout = QtGui.QGridLayout(GdalToolsWidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.batchCheck = QtGui.QCheckBox(GdalToolsWidget)
        self.batchCheck.setObjectName(_fromUtf8("batchCheck"))
        self.gridLayout.addWidget(self.batchCheck, 0, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label = QtGui.QLabel(GdalToolsWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(GdalToolsWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.sourceSRSCheck = QtGui.QCheckBox(GdalToolsWidget)
        self.sourceSRSCheck.setObjectName(_fromUtf8("sourceSRSCheck"))
        self.gridLayout_2.addWidget(self.sourceSRSCheck, 2, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.sourceSRSEdit = QtGui.QLineEdit(GdalToolsWidget)
        self.sourceSRSEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.sourceSRSEdit.setObjectName(_fromUtf8("sourceSRSEdit"))
        self.horizontalLayout.addWidget(self.sourceSRSEdit)
        self.selectSourceSRSButton = QtGui.QPushButton(GdalToolsWidget)
        self.selectSourceSRSButton.setObjectName(_fromUtf8("selectSourceSRSButton"))
        self.horizontalLayout.addWidget(self.selectSourceSRSButton)
        self.gridLayout_2.addLayout(self.horizontalLayout, 2, 1, 1, 1)
        self.targetSRSCheck = QtGui.QCheckBox(GdalToolsWidget)
        self.targetSRSCheck.setObjectName(_fromUtf8("targetSRSCheck"))
        self.gridLayout_2.addWidget(self.targetSRSCheck, 3, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.targetSRSEdit = QtGui.QLineEdit(GdalToolsWidget)
        self.targetSRSEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.targetSRSEdit.setObjectName(_fromUtf8("targetSRSEdit"))
        self.horizontalLayout_4.addWidget(self.targetSRSEdit)
        self.selectTargetSRSButton = QtGui.QPushButton(GdalToolsWidget)
        self.selectTargetSRSButton.setObjectName(_fromUtf8("selectTargetSRSButton"))
        self.horizontalLayout_4.addWidget(self.selectTargetSRSButton)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 3, 1, 1, 1)
        self.resamplingCheck = QtGui.QCheckBox(GdalToolsWidget)
        self.resamplingCheck.setObjectName(_fromUtf8("resamplingCheck"))
        self.gridLayout_2.addWidget(self.resamplingCheck, 4, 0, 1, 1)
        self.resamplingCombo = QtGui.QComboBox(GdalToolsWidget)
        self.resamplingCombo.setObjectName(_fromUtf8("resamplingCombo"))
        self.resamplingCombo.addItem(_fromUtf8(""))
        self.resamplingCombo.addItem(_fromUtf8(""))
        self.resamplingCombo.addItem(_fromUtf8(""))
        self.resamplingCombo.addItem(_fromUtf8(""))
        self.resamplingCombo.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.resamplingCombo, 4, 1, 1, 1)
        self.noDataCheck = QtGui.QCheckBox(GdalToolsWidget)
        self.noDataCheck.setObjectName(_fromUtf8("noDataCheck"))
        self.gridLayout_2.addWidget(self.noDataCheck, 5, 0, 1, 1)
        self.noDataEdit = QtGui.QLineEdit(GdalToolsWidget)
        self.noDataEdit.setObjectName(_fromUtf8("noDataEdit"))
        self.gridLayout_2.addWidget(self.noDataEdit, 5, 1, 1, 1)
        self.cacheCheck = QtGui.QCheckBox(GdalToolsWidget)
        self.cacheCheck.setObjectName(_fromUtf8("cacheCheck"))
        self.gridLayout_2.addWidget(self.cacheCheck, 7, 0, 1, 1)
        self.cacheSpin = QtGui.QSpinBox(GdalToolsWidget)
        self.cacheSpin.setMinimum(20)
        self.cacheSpin.setMaximum(1024)
        self.cacheSpin.setObjectName(_fromUtf8("cacheSpin"))
        self.gridLayout_2.addWidget(self.cacheSpin, 7, 1, 1, 1)
        self.maskCheck = QtGui.QCheckBox(GdalToolsWidget)
        self.maskCheck.setObjectName(_fromUtf8("maskCheck"))
        self.gridLayout_2.addWidget(self.maskCheck, 6, 0, 1, 1)
        self.inSelector = GdalToolsInOutSelector(GdalToolsWidget)
        self.inSelector.setObjectName(_fromUtf8("inSelector"))
        self.gridLayout_2.addWidget(self.inSelector, 0, 1, 1, 1)
        self.outSelector = GdalToolsInOutSelector(GdalToolsWidget)
        self.outSelector.setObjectName(_fromUtf8("outSelector"))
        self.gridLayout_2.addWidget(self.outSelector, 1, 1, 1, 1)
        self.maskSelector = GdalToolsInOutSelector(GdalToolsWidget)
        self.maskSelector.setObjectName(_fromUtf8("maskSelector"))
        self.gridLayout_2.addWidget(self.maskSelector, 6, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.resizeGroupBox = QtGui.QGroupBox(GdalToolsWidget)
        self.resizeGroupBox.setCheckable(True)
        self.resizeGroupBox.setChecked(False)
        self.resizeGroupBox.setObjectName(_fromUtf8("resizeGroupBox"))
        self.gridLayout_7 = QtGui.QGridLayout(self.resizeGroupBox)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_11 = QtGui.QLabel(self.resizeGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_7.addWidget(self.label_11, 0, 0, 1, 1)
        self.widthSpin = QtGui.QSpinBox(self.resizeGroupBox)
        self.widthSpin.setMaximum(999999)
        self.widthSpin.setObjectName(_fromUtf8("widthSpin"))
        self.gridLayout_7.addWidget(self.widthSpin, 0, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.resizeGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setIndent(40)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_7.addWidget(self.label_12, 0, 2, 1, 1)
        self.heightSpin = QtGui.QSpinBox(self.resizeGroupBox)
        self.heightSpin.setMaximum(999999)
        self.heightSpin.setObjectName(_fromUtf8("heightSpin"))
        self.gridLayout_7.addWidget(self.heightSpin, 0, 3, 1, 1)
        self.gridLayout.addWidget(self.resizeGroupBox, 2, 0, 1, 1)
        self.progressBar = QtGui.QProgressBar(GdalToolsWidget)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.gridLayout.addWidget(self.progressBar, 3, 0, 1, 1)
        self.multithreadCheck = QtGui.QCheckBox(GdalToolsWidget)
        self.multithreadCheck.setObjectName(_fromUtf8("multithreadCheck"))
        self.gridLayout.addWidget(self.multithreadCheck, 4, 0, 1, 1)
        self.label.setBuddy(self.inSelector)
        self.label_2.setBuddy(self.outSelector)

        self.retranslateUi(GdalToolsWidget)
        QtCore.QMetaObject.connectSlotsByName(GdalToolsWidget)

    def retranslateUi(self, GdalToolsWidget):
        GdalToolsWidget.setWindowTitle(_translate("GdalToolsWidget", "Warp (Reproject)", None))
        self.batchCheck.setText(_translate("GdalToolsWidget", "Batch mode (for processing whole directory)", None))
        self.label.setText(_translate("GdalToolsWidget", "&Input file", None))
        self.label_2.setText(_translate("GdalToolsWidget", "&Output file", None))
        self.sourceSRSCheck.setText(_translate("GdalToolsWidget", "&Source SRS", None))
        self.selectSourceSRSButton.setText(_translate("GdalToolsWidget", "Select...", None))
        self.targetSRSCheck.setText(_translate("GdalToolsWidget", "&Target SRS", None))
        self.selectTargetSRSButton.setText(_translate("GdalToolsWidget", "Select...", None))
        self.resamplingCheck.setText(_translate("GdalToolsWidget", "&Resampling method", None))
        self.resamplingCombo.setItemText(0, _translate("GdalToolsWidget", "Near", None))
        self.resamplingCombo.setItemText(1, _translate("GdalToolsWidget", "Bilinear", None))
        self.resamplingCombo.setItemText(2, _translate("GdalToolsWidget", "Cubic", None))
        self.resamplingCombo.setItemText(3, _translate("GdalToolsWidget", "Cubic spline", None))
        self.resamplingCombo.setItemText(4, _translate("GdalToolsWidget", "Lanczos", None))
        self.noDataCheck.setText(_translate("GdalToolsWidget", "No data values", None))
        self.noDataEdit.setText(_translate("GdalToolsWidget", "0", None))
        self.cacheCheck.setText(_translate("GdalToolsWidget", "&Memory used for caching", None))
        self.cacheSpin.setSuffix(_translate("GdalToolsWidget", "MB", None))
        self.maskCheck.setText(_translate("GdalToolsWidget", "Mask layer", None))
        self.resizeGroupBox.setTitle(_translate("GdalToolsWidget", "Resize", None))
        self.label_11.setText(_translate("GdalToolsWidget", "Width", None))
        self.label_12.setText(_translate("GdalToolsWidget", "Height", None))
        self.multithreadCheck.setText(_translate("GdalToolsWidget", "Use m&ultithreaded warping implementation", None))

from .inOutSelector import GdalToolsInOutSelector
