# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/src/qgis/python/plugins/GdalTools/tools/widgetGrid.ui'
#
# Created: Sat Jun 23 08:09:33 2018
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_GdalToolsWidget(object):
    def setupUi(self, GdalToolsWidget):
        GdalToolsWidget.setObjectName(_fromUtf8("GdalToolsWidget"))
        GdalToolsWidget.resize(777, 348)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(GdalToolsWidget.sizePolicy().hasHeightForWidth())
        GdalToolsWidget.setSizePolicy(sizePolicy)
        self.verticalLayout = QtGui.QVBoxLayout(GdalToolsWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(GdalToolsWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.zfieldCheck = QtGui.QCheckBox(GdalToolsWidget)
        self.zfieldCheck.setObjectName(_fromUtf8("zfieldCheck"))
        self.gridLayout.addWidget(self.zfieldCheck, 1, 0, 1, 1)
        self.zfieldCombo = QtGui.QComboBox(GdalToolsWidget)
        self.zfieldCombo.setObjectName(_fromUtf8("zfieldCombo"))
        self.gridLayout.addWidget(self.zfieldCombo, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(GdalToolsWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.algorithmCheck = QtGui.QCheckBox(GdalToolsWidget)
        self.algorithmCheck.setObjectName(_fromUtf8("algorithmCheck"))
        self.gridLayout.addWidget(self.algorithmCheck, 3, 0, 1, 1)
        self.algorithmCombo = QtGui.QComboBox(GdalToolsWidget)
        self.algorithmCombo.setObjectName(_fromUtf8("algorithmCombo"))
        self.algorithmCombo.addItem(_fromUtf8(""))
        self.algorithmCombo.addItem(_fromUtf8(""))
        self.algorithmCombo.addItem(_fromUtf8(""))
        self.algorithmCombo.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.algorithmCombo, 3, 1, 1, 1)
        self.inSelector = GdalToolsInOutSelector(GdalToolsWidget)
        self.inSelector.setObjectName(_fromUtf8("inSelector"))
        self.gridLayout.addWidget(self.inSelector, 0, 1, 1, 1)
        self.outSelector = GdalToolsInOutSelector(GdalToolsWidget)
        self.outSelector.setObjectName(_fromUtf8("outSelector"))
        self.gridLayout.addWidget(self.outSelector, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.stackedWidget = QtGui.QStackedWidget(GdalToolsWidget)
        self.stackedWidget.setFrameShape(QtGui.QFrame.NoFrame)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.gridLayout_3 = QtGui.QGridLayout(self.page)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_3 = QtGui.QLabel(self.page)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.invdistPowerSpin = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.invdistPowerSpin.sizePolicy().hasHeightForWidth())
        self.invdistPowerSpin.setSizePolicy(sizePolicy)
        self.invdistPowerSpin.setDecimals(1)
        self.invdistPowerSpin.setObjectName(_fromUtf8("invdistPowerSpin"))
        self.gridLayout_3.addWidget(self.invdistPowerSpin, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.page)
        self.label_4.setIndent(30)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 0, 2, 1, 1)
        self.invdistSmothingSpin = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.invdistSmothingSpin.sizePolicy().hasHeightForWidth())
        self.invdistSmothingSpin.setSizePolicy(sizePolicy)
        self.invdistSmothingSpin.setDecimals(1)
        self.invdistSmothingSpin.setMaximum(65000.0)
        self.invdistSmothingSpin.setObjectName(_fromUtf8("invdistSmothingSpin"))
        self.gridLayout_3.addWidget(self.invdistSmothingSpin, 0, 3, 1, 1)
        self.label_5 = QtGui.QLabel(self.page)
        self.label_5.setIndent(30)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 0, 4, 1, 1)
        self.invdistRadius1Spin = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.invdistRadius1Spin.sizePolicy().hasHeightForWidth())
        self.invdistRadius1Spin.setSizePolicy(sizePolicy)
        self.invdistRadius1Spin.setDecimals(1)
        self.invdistRadius1Spin.setMaximum(65000.0)
        self.invdistRadius1Spin.setObjectName(_fromUtf8("invdistRadius1Spin"))
        self.gridLayout_3.addWidget(self.invdistRadius1Spin, 0, 5, 1, 1)
        self.label_6 = QtGui.QLabel(self.page)
        self.label_6.setIndent(30)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 0, 6, 1, 1)
        self.invdistRadius2Spin = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.invdistRadius2Spin.sizePolicy().hasHeightForWidth())
        self.invdistRadius2Spin.setSizePolicy(sizePolicy)
        self.invdistRadius2Spin.setDecimals(1)
        self.invdistRadius2Spin.setMaximum(65000.0)
        self.invdistRadius2Spin.setObjectName(_fromUtf8("invdistRadius2Spin"))
        self.gridLayout_3.addWidget(self.invdistRadius2Spin, 0, 7, 1, 1)
        self.label_8 = QtGui.QLabel(self.page)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 1, 0, 1, 1)
        self.invdistMaxPointsSpin = QtGui.QSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.invdistMaxPointsSpin.sizePolicy().hasHeightForWidth())
        self.invdistMaxPointsSpin.setSizePolicy(sizePolicy)
        self.invdistMaxPointsSpin.setMaximum(65000)
        self.invdistMaxPointsSpin.setObjectName(_fromUtf8("invdistMaxPointsSpin"))
        self.gridLayout_3.addWidget(self.invdistMaxPointsSpin, 1, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.page)
        self.label_9.setIndent(30)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_3.addWidget(self.label_9, 1, 2, 1, 1)
        self.invdistMinPointsSpin = QtGui.QSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.invdistMinPointsSpin.sizePolicy().hasHeightForWidth())
        self.invdistMinPointsSpin.setSizePolicy(sizePolicy)
        self.invdistMinPointsSpin.setMaximum(65000)
        self.invdistMinPointsSpin.setObjectName(_fromUtf8("invdistMinPointsSpin"))
        self.gridLayout_3.addWidget(self.invdistMinPointsSpin, 1, 3, 1, 1)
        self.label_7 = QtGui.QLabel(self.page)
        self.label_7.setIndent(30)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 1, 4, 1, 1)
        self.invdistAngleSpin = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.invdistAngleSpin.sizePolicy().hasHeightForWidth())
        self.invdistAngleSpin.setSizePolicy(sizePolicy)
        self.invdistAngleSpin.setDecimals(1)
        self.invdistAngleSpin.setMaximum(359.0)
        self.invdistAngleSpin.setObjectName(_fromUtf8("invdistAngleSpin"))
        self.gridLayout_3.addWidget(self.invdistAngleSpin, 1, 5, 1, 1)
        self.label_10 = QtGui.QLabel(self.page)
        self.label_10.setIndent(30)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_3.addWidget(self.label_10, 1, 6, 1, 1)
        self.invdistNoDataSpin = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.invdistNoDataSpin.sizePolicy().hasHeightForWidth())
        self.invdistNoDataSpin.setSizePolicy(sizePolicy)
        self.invdistNoDataSpin.setDecimals(1)
        self.invdistNoDataSpin.setMinimum(-100000.0)
        self.invdistNoDataSpin.setMaximum(65000.0)
        self.invdistNoDataSpin.setObjectName(_fromUtf8("invdistNoDataSpin"))
        self.gridLayout_3.addWidget(self.invdistNoDataSpin, 1, 7, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 2, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.page_2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_21 = QtGui.QLabel(self.page_2)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_4.addWidget(self.label_21, 0, 0, 1, 1)
        self.averageRadius1Spin = QtGui.QDoubleSpinBox(self.page_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.averageRadius1Spin.sizePolicy().hasHeightForWidth())
        self.averageRadius1Spin.setSizePolicy(sizePolicy)
        self.averageRadius1Spin.setDecimals(1)
        self.averageRadius1Spin.setMaximum(65000.0)
        self.averageRadius1Spin.setObjectName(_fromUtf8("averageRadius1Spin"))
        self.gridLayout_4.addWidget(self.averageRadius1Spin, 0, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.page_2)
        self.label_19.setIndent(40)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_4.addWidget(self.label_19, 0, 2, 1, 1)
        self.averageRadius2Spin = QtGui.QDoubleSpinBox(self.page_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.averageRadius2Spin.sizePolicy().hasHeightForWidth())
        self.averageRadius2Spin.setSizePolicy(sizePolicy)
        self.averageRadius2Spin.setDecimals(1)
        self.averageRadius2Spin.setMaximum(65000.0)
        self.averageRadius2Spin.setObjectName(_fromUtf8("averageRadius2Spin"))
        self.gridLayout_4.addWidget(self.averageRadius2Spin, 0, 3, 1, 1)
        self.label_22 = QtGui.QLabel(self.page_2)
        self.label_22.setIndent(40)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_4.addWidget(self.label_22, 0, 4, 1, 1)
        self.averageAngleSpin = QtGui.QDoubleSpinBox(self.page_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.averageAngleSpin.sizePolicy().hasHeightForWidth())
        self.averageAngleSpin.setSizePolicy(sizePolicy)
        self.averageAngleSpin.setDecimals(1)
        self.averageAngleSpin.setMaximum(359.0)
        self.averageAngleSpin.setObjectName(_fromUtf8("averageAngleSpin"))
        self.gridLayout_4.addWidget(self.averageAngleSpin, 0, 5, 1, 1)
        self.label_20 = QtGui.QLabel(self.page_2)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_4.addWidget(self.label_20, 1, 0, 1, 1)
        self.averageMinPointsSpin = QtGui.QSpinBox(self.page_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.averageMinPointsSpin.sizePolicy().hasHeightForWidth())
        self.averageMinPointsSpin.setSizePolicy(sizePolicy)
        self.averageMinPointsSpin.setMaximum(65000)
        self.averageMinPointsSpin.setObjectName(_fromUtf8("averageMinPointsSpin"))
        self.gridLayout_4.addWidget(self.averageMinPointsSpin, 1, 1, 1, 1)
        self.label_23 = QtGui.QLabel(self.page_2)
        self.label_23.setIndent(40)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_4.addWidget(self.label_23, 1, 2, 1, 1)
        self.averageNoDataSpin = QtGui.QDoubleSpinBox(self.page_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.averageNoDataSpin.sizePolicy().hasHeightForWidth())
        self.averageNoDataSpin.setSizePolicy(sizePolicy)
        self.averageNoDataSpin.setDecimals(1)
        self.averageNoDataSpin.setMaximum(65000.0)
        self.averageNoDataSpin.setObjectName(_fromUtf8("averageNoDataSpin"))
        self.gridLayout_4.addWidget(self.averageNoDataSpin, 1, 3, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem1, 2, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.page_5 = QtGui.QWidget()
        self.page_5.setObjectName(_fromUtf8("page_5"))
        self.gridLayout_5 = QtGui.QGridLayout(self.page_5)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_26 = QtGui.QLabel(self.page_5)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_5.addWidget(self.label_26, 0, 0, 1, 1)
        self.nearestRadius1Spin = QtGui.QDoubleSpinBox(self.page_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nearestRadius1Spin.sizePolicy().hasHeightForWidth())
        self.nearestRadius1Spin.setSizePolicy(sizePolicy)
        self.nearestRadius1Spin.setDecimals(1)
        self.nearestRadius1Spin.setMaximum(65000.0)
        self.nearestRadius1Spin.setObjectName(_fromUtf8("nearestRadius1Spin"))
        self.gridLayout_5.addWidget(self.nearestRadius1Spin, 0, 1, 1, 1)
        self.label_24 = QtGui.QLabel(self.page_5)
        self.label_24.setIndent(40)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_5.addWidget(self.label_24, 0, 2, 1, 1)
        self.nearestRadius2Spin = QtGui.QDoubleSpinBox(self.page_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nearestRadius2Spin.sizePolicy().hasHeightForWidth())
        self.nearestRadius2Spin.setSizePolicy(sizePolicy)
        self.nearestRadius2Spin.setDecimals(1)
        self.nearestRadius2Spin.setMaximum(65000.0)
        self.nearestRadius2Spin.setObjectName(_fromUtf8("nearestRadius2Spin"))
        self.gridLayout_5.addWidget(self.nearestRadius2Spin, 0, 3, 1, 1)
        self.label_27 = QtGui.QLabel(self.page_5)
        self.label_27.setIndent(40)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_5.addWidget(self.label_27, 0, 4, 1, 1)
        self.nearestAngleSpin = QtGui.QDoubleSpinBox(self.page_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nearestAngleSpin.sizePolicy().hasHeightForWidth())
        self.nearestAngleSpin.setSizePolicy(sizePolicy)
        self.nearestAngleSpin.setDecimals(1)
        self.nearestAngleSpin.setMaximum(359.0)
        self.nearestAngleSpin.setObjectName(_fromUtf8("nearestAngleSpin"))
        self.gridLayout_5.addWidget(self.nearestAngleSpin, 0, 5, 1, 1)
        self.label_28 = QtGui.QLabel(self.page_5)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_5.addWidget(self.label_28, 1, 0, 1, 1)
        self.nearestNoDataSpin = QtGui.QDoubleSpinBox(self.page_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nearestNoDataSpin.sizePolicy().hasHeightForWidth())
        self.nearestNoDataSpin.setSizePolicy(sizePolicy)
        self.nearestNoDataSpin.setDecimals(1)
        self.nearestNoDataSpin.setMaximum(65000.0)
        self.nearestNoDataSpin.setObjectName(_fromUtf8("nearestNoDataSpin"))
        self.gridLayout_5.addWidget(self.nearestNoDataSpin, 1, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem2, 2, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtGui.QWidget()
        self.page_6.setObjectName(_fromUtf8("page_6"))
        self.gridLayout_6 = QtGui.QGridLayout(self.page_6)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_25 = QtGui.QLabel(self.page_6)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_6.addWidget(self.label_25, 0, 0, 1, 1)
        self.datametricsCombo = QtGui.QComboBox(self.page_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datametricsCombo.sizePolicy().hasHeightForWidth())
        self.datametricsCombo.setSizePolicy(sizePolicy)
        self.datametricsCombo.setObjectName(_fromUtf8("datametricsCombo"))
        self.datametricsCombo.addItem(_fromUtf8(""))
        self.datametricsCombo.addItem(_fromUtf8(""))
        self.datametricsCombo.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.datametricsCombo, 0, 1, 1, 1)
        self.label_31 = QtGui.QLabel(self.page_6)
        self.label_31.setIndent(40)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_6.addWidget(self.label_31, 0, 2, 1, 1)
        self.datametricsRadius1Spin = QtGui.QDoubleSpinBox(self.page_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datametricsRadius1Spin.sizePolicy().hasHeightForWidth())
        self.datametricsRadius1Spin.setSizePolicy(sizePolicy)
        self.datametricsRadius1Spin.setDecimals(1)
        self.datametricsRadius1Spin.setMaximum(65000.0)
        self.datametricsRadius1Spin.setObjectName(_fromUtf8("datametricsRadius1Spin"))
        self.gridLayout_6.addWidget(self.datametricsRadius1Spin, 0, 3, 1, 1)
        self.label_29 = QtGui.QLabel(self.page_6)
        self.label_29.setIndent(40)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_6.addWidget(self.label_29, 0, 4, 1, 1)
        self.datametricsRadius2Spin = QtGui.QDoubleSpinBox(self.page_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datametricsRadius2Spin.sizePolicy().hasHeightForWidth())
        self.datametricsRadius2Spin.setSizePolicy(sizePolicy)
        self.datametricsRadius2Spin.setDecimals(1)
        self.datametricsRadius2Spin.setMaximum(65000.0)
        self.datametricsRadius2Spin.setObjectName(_fromUtf8("datametricsRadius2Spin"))
        self.gridLayout_6.addWidget(self.datametricsRadius2Spin, 0, 5, 1, 1)
        self.label_32 = QtGui.QLabel(self.page_6)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_6.addWidget(self.label_32, 1, 0, 1, 1)
        self.datametricsAngleSpin = QtGui.QDoubleSpinBox(self.page_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datametricsAngleSpin.sizePolicy().hasHeightForWidth())
        self.datametricsAngleSpin.setSizePolicy(sizePolicy)
        self.datametricsAngleSpin.setDecimals(1)
        self.datametricsAngleSpin.setMaximum(359.0)
        self.datametricsAngleSpin.setObjectName(_fromUtf8("datametricsAngleSpin"))
        self.gridLayout_6.addWidget(self.datametricsAngleSpin, 1, 1, 1, 1)
        self.label_33 = QtGui.QLabel(self.page_6)
        self.label_33.setIndent(40)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_6.addWidget(self.label_33, 1, 2, 1, 1)
        self.datametricsNoDataSpin = QtGui.QDoubleSpinBox(self.page_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datametricsNoDataSpin.sizePolicy().hasHeightForWidth())
        self.datametricsNoDataSpin.setSizePolicy(sizePolicy)
        self.datametricsNoDataSpin.setDecimals(1)
        self.datametricsNoDataSpin.setMaximum(65000.0)
        self.datametricsNoDataSpin.setObjectName(_fromUtf8("datametricsNoDataSpin"))
        self.gridLayout_6.addWidget(self.datametricsNoDataSpin, 1, 3, 1, 1)
        self.label_30 = QtGui.QLabel(self.page_6)
        self.label_30.setIndent(40)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_6.addWidget(self.label_30, 1, 4, 1, 1)
        self.datametricsMinPointsSpin = QtGui.QSpinBox(self.page_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datametricsMinPointsSpin.sizePolicy().hasHeightForWidth())
        self.datametricsMinPointsSpin.setSizePolicy(sizePolicy)
        self.datametricsMinPointsSpin.setMaximum(65000)
        self.datametricsMinPointsSpin.setObjectName(_fromUtf8("datametricsMinPointsSpin"))
        self.gridLayout_6.addWidget(self.datametricsMinPointsSpin, 1, 5, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem3, 2, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_6)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.resizeGroupBox = QtGui.QGroupBox(GdalToolsWidget)
        self.resizeGroupBox.setCheckable(True)
        self.resizeGroupBox.setChecked(False)
        self.resizeGroupBox.setObjectName(_fromUtf8("resizeGroupBox"))
        self.gridLayout_7 = QtGui.QGridLayout(self.resizeGroupBox)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_11 = QtGui.QLabel(self.resizeGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_7.addWidget(self.label_11, 0, 0, 1, 1)
        self.widthSpin = QtGui.QSpinBox(self.resizeGroupBox)
        self.widthSpin.setMaximum(999999)
        self.widthSpin.setObjectName(_fromUtf8("widthSpin"))
        self.gridLayout_7.addWidget(self.widthSpin, 0, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.resizeGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setIndent(40)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_7.addWidget(self.label_12, 0, 2, 1, 1)
        self.heightSpin = QtGui.QSpinBox(self.resizeGroupBox)
        self.heightSpin.setMaximum(999999)
        self.heightSpin.setObjectName(_fromUtf8("heightSpin"))
        self.gridLayout_7.addWidget(self.heightSpin, 0, 3, 1, 1)
        self.verticalLayout.addWidget(self.resizeGroupBox)
        self.extentGroup = QtGui.QGroupBox(GdalToolsWidget)
        self.extentGroup.setCheckable(True)
        self.extentGroup.setChecked(False)
        self.extentGroup.setObjectName(_fromUtf8("extentGroup"))
        self.gridLayout_2 = QtGui.QGridLayout(self.extentGroup)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.extentSelector = GdalToolsExtentSelector(self.extentGroup)
        self.extentSelector.setObjectName(_fromUtf8("extentSelector"))
        self.gridLayout_2.addWidget(self.extentSelector, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.extentGroup)
        self.label.setBuddy(self.inSelector)
        self.label_2.setBuddy(self.outSelector)

        self.retranslateUi(GdalToolsWidget)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.algorithmCombo, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.stackedWidget.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(GdalToolsWidget)

    def retranslateUi(self, GdalToolsWidget):
        GdalToolsWidget.setWindowTitle(_translate("GdalToolsWidget", "Grid (Interpolation)", None))
        self.label.setText(_translate("GdalToolsWidget", "&Input file", None))
        self.zfieldCheck.setText(_translate("GdalToolsWidget", "&Z Field", None))
        self.label_2.setText(_translate("GdalToolsWidget", "&Output file", None))
        self.algorithmCheck.setText(_translate("GdalToolsWidget", "&Algorithm", None))
        self.algorithmCombo.setItemText(0, _translate("GdalToolsWidget", "Inverse distance to a power", None))
        self.algorithmCombo.setItemText(1, _translate("GdalToolsWidget", "Moving average", None))
        self.algorithmCombo.setItemText(2, _translate("GdalToolsWidget", "Nearest neighbor", None))
        self.algorithmCombo.setItemText(3, _translate("GdalToolsWidget", "Data metrics", None))
        self.label_3.setText(_translate("GdalToolsWidget", "Power", None))
        self.label_4.setText(_translate("GdalToolsWidget", "Smoothing", None))
        self.label_5.setText(_translate("GdalToolsWidget", "Radius1", None))
        self.label_6.setText(_translate("GdalToolsWidget", "Radius2", None))
        self.label_8.setText(_translate("GdalToolsWidget", "Max points", None))
        self.label_9.setText(_translate("GdalToolsWidget", "Min points", None))
        self.label_7.setText(_translate("GdalToolsWidget", "Angle", None))
        self.label_10.setText(_translate("GdalToolsWidget", "No data", None))
        self.label_21.setText(_translate("GdalToolsWidget", "Radius1", None))
        self.label_19.setText(_translate("GdalToolsWidget", "Radius2", None))
        self.label_22.setText(_translate("GdalToolsWidget", "Angle", None))
        self.label_20.setText(_translate("GdalToolsWidget", "Min points", None))
        self.label_23.setText(_translate("GdalToolsWidget", "No data", None))
        self.label_26.setText(_translate("GdalToolsWidget", "Radius1", None))
        self.label_24.setText(_translate("GdalToolsWidget", "Radius2", None))
        self.label_27.setText(_translate("GdalToolsWidget", "Angle", None))
        self.label_28.setText(_translate("GdalToolsWidget", "No data", None))
        self.label_25.setText(_translate("GdalToolsWidget", "Metrics", None))
        self.datametricsCombo.setItemText(0, _translate("GdalToolsWidget", "Minimum", None))
        self.datametricsCombo.setItemText(1, _translate("GdalToolsWidget", "Maximum", None))
        self.datametricsCombo.setItemText(2, _translate("GdalToolsWidget", "Range", None))
        self.label_31.setText(_translate("GdalToolsWidget", "Radius1", None))
        self.label_29.setText(_translate("GdalToolsWidget", "Radius2", None))
        self.label_32.setText(_translate("GdalToolsWidget", "Angle", None))
        self.label_33.setText(_translate("GdalToolsWidget", "No data", None))
        self.label_30.setText(_translate("GdalToolsWidget", "Min points", None))
        self.resizeGroupBox.setTitle(_translate("GdalToolsWidget", "Resize", None))
        self.label_11.setText(_translate("GdalToolsWidget", "Width", None))
        self.label_12.setText(_translate("GdalToolsWidget", "Height", None))
        self.extentGroup.setTitle(_translate("GdalToolsWidget", "Extent", None))

from .inOutSelector import GdalToolsInOutSelector
from .extentSelector import GdalToolsExtentSelector
