# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/src/qgis/python/console/console_settings.ui'
#
# Created: Sat Jun 23 07:59:28 2018
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SettingsDialogPythonConsole(object):
    def setupUi(self, SettingsDialogPythonConsole):
        SettingsDialogPythonConsole.setObjectName(_fromUtf8("SettingsDialogPythonConsole"))
        SettingsDialogPythonConsole.setWindowModality(QtCore.Qt.NonModal)
        SettingsDialogPythonConsole.resize(583, 569)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SettingsDialogPythonConsole.sizePolicy().hasHeightForWidth())
        SettingsDialogPythonConsole.setSizePolicy(sizePolicy)
        SettingsDialogPythonConsole.setMinimumSize(QtCore.QSize(500, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        SettingsDialogPythonConsole.setFont(font)
        SettingsDialogPythonConsole.setModal(True)
        self.gridLayout_6 = QtGui.QGridLayout(SettingsDialogPythonConsole)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.buttonBox = QtGui.QDialogButtonBox(SettingsDialogPythonConsole)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_6.addWidget(self.buttonBox, 1, 0, 1, 1)
        self.scrollArea = QtGui.QScrollArea(SettingsDialogPythonConsole)
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -370, 554, 1302))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_2 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.groupBox_2 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.preloadAPI = QtGui.QCheckBox(self.groupBox_2)
        self.preloadAPI.setChecked(True)
        self.preloadAPI.setObjectName(_fromUtf8("preloadAPI"))
        self.gridLayout_7.addWidget(self.preloadAPI, 0, 0, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.addAPIpath = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addAPIpath.sizePolicy().hasHeightForWidth())
        self.addAPIpath.setSizePolicy(sizePolicy)
        self.addAPIpath.setMinimumSize(QtCore.QSize(32, 32))
        self.addAPIpath.setMaximumSize(QtCore.QSize(32, 32))
        self.addAPIpath.setText(_fromUtf8(""))
        self.addAPIpath.setObjectName(_fromUtf8("addAPIpath"))
        self.verticalLayout.addWidget(self.addAPIpath)
        self.removeAPIpath = QtGui.QPushButton(self.groupBox_2)
        self.removeAPIpath.setMinimumSize(QtCore.QSize(32, 32))
        self.removeAPIpath.setMaximumSize(QtCore.QSize(32, 32))
        self.removeAPIpath.setText(_fromUtf8(""))
        self.removeAPIpath.setObjectName(_fromUtf8("removeAPIpath"))
        self.verticalLayout.addWidget(self.removeAPIpath)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.tableWidget = QtGui.QTableWidget(self.groupBox_2)
        self.tableWidget.setMinimumSize(QtCore.QSize(0, 150))
        self.tableWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setTabKeyNavigation(False)
        self.tableWidget.setProperty("showDropIndicator", False)
        self.tableWidget.setDragDropOverwriteMode(False)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.tableWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidget.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.tableWidget.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.groupBoxPreparedAPI = QgsCollapsibleGroupBox(self.groupBox_2)
        self.groupBoxPreparedAPI.setCheckable(True)
        self.groupBoxPreparedAPI.setChecked(False)
        self.groupBoxPreparedAPI.setProperty("collapsed", True)
        self.groupBoxPreparedAPI.setProperty("saveCollapsedState", True)
        self.groupBoxPreparedAPI.setProperty("saveCheckedState", True)
        self.groupBoxPreparedAPI.setObjectName(_fromUtf8("groupBoxPreparedAPI"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBoxPreparedAPI)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.compileAPIs = QtGui.QPushButton(self.groupBoxPreparedAPI)
        self.compileAPIs.setObjectName(_fromUtf8("compileAPIs"))
        self.gridLayout_3.addWidget(self.compileAPIs, 0, 0, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.groupBoxPreparedAPI)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 27))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout_3.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.gridLayout_7.addWidget(self.groupBoxPreparedAPI, 2, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 2, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_10 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.autoSaveScript = QtGui.QCheckBox(self.groupBox_3)
        self.autoSaveScript.setObjectName(_fromUtf8("autoSaveScript"))
        self.gridLayout_10.addWidget(self.autoSaveScript, 1, 0, 1, 1)
        self.enableObjectInspector = QtGui.QCheckBox(self.groupBox_3)
        self.enableObjectInspector.setChecked(False)
        self.enableObjectInspector.setObjectName(_fromUtf8("enableObjectInspector"))
        self.gridLayout_10.addWidget(self.enableObjectInspector, 0, 0, 1, 1)
        self.groupBoxFontColorEditor = QgsCollapsibleGroupBox(self.groupBox_3)
        self.groupBoxFontColorEditor.setProperty("collapsed", False)
        self.groupBoxFontColorEditor.setProperty("saveCollapsedState", True)
        self.groupBoxFontColorEditor.setObjectName(_fromUtf8("groupBoxFontColorEditor"))
        self.gridLayout_14 = QtGui.QGridLayout(self.groupBoxFontColorEditor)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_4 = QtGui.QLabel(self.groupBoxFontColorEditor)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_3.addWidget(self.label_4)
        self.fontComboBoxEditor = QtGui.QFontComboBox(self.groupBoxFontColorEditor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fontComboBoxEditor.sizePolicy().hasHeightForWidth())
        self.fontComboBoxEditor.setSizePolicy(sizePolicy)
        self.fontComboBoxEditor.setInsertPolicy(QtGui.QComboBox.NoInsert)
        self.fontComboBoxEditor.setObjectName(_fromUtf8("fontComboBoxEditor"))
        self.horizontalLayout_3.addWidget(self.fontComboBoxEditor)
        self.label_5 = QtGui.QLabel(self.groupBoxFontColorEditor)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_3.addWidget(self.label_5)
        self.spinBoxEditor = QtGui.QSpinBox(self.groupBoxFontColorEditor)
        self.spinBoxEditor.setMinimumSize(QtCore.QSize(51, 26))
        self.spinBoxEditor.setMaximumSize(QtCore.QSize(51, 26))
        self.spinBoxEditor.setMinimum(6)
        self.spinBoxEditor.setMaximum(15)
        self.spinBoxEditor.setProperty("value", 10)
        self.spinBoxEditor.setObjectName(_fromUtf8("spinBoxEditor"))
        self.horizontalLayout_3.addWidget(self.spinBoxEditor)
        self.gridLayout_14.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.gridLayout_13 = QtGui.QGridLayout()
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.label_7 = QtGui.QLabel(self.groupBoxFontColorEditor)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_13.addWidget(self.label_7, 0, 0, 1, 1)
        self.defaultFontColorEditor = QgsColorButton(self.groupBoxFontColorEditor)
        self.defaultFontColorEditor.setText(_fromUtf8(""))
        self.defaultFontColorEditor.setObjectName(_fromUtf8("defaultFontColorEditor"))
        self.gridLayout_13.addWidget(self.defaultFontColorEditor, 0, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBoxFontColorEditor)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_13.addWidget(self.label_8, 0, 2, 1, 1)
        self.keywordFontColorEditor = QgsColorButton(self.groupBoxFontColorEditor)
        self.keywordFontColorEditor.setText(_fromUtf8(""))
        self.keywordFontColorEditor.setObjectName(_fromUtf8("keywordFontColorEditor"))
        self.gridLayout_13.addWidget(self.keywordFontColorEditor, 0, 3, 1, 1)
        self.label_27 = QtGui.QLabel(self.groupBoxFontColorEditor)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_13.addWidget(self.label_27, 0, 4, 1, 1)
        self.classFontColorEditor = QgsColorButton(self.groupBoxFontColorEditor)
        self.classFontColorEditor.setText(_fromUtf8(""))
        self.classFontColorEditor.setObjectName(_fromUtf8("classFontColorEditor"))
        self.gridLayout_13.addWidget(self.classFontColorEditor, 0, 5, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBoxFontColorEditor)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_13.addWidget(self.label_11, 1, 0, 1, 1)
        self.methodFontColorEditor = QgsColorButton(self.groupBoxFontColorEditor)
        self.methodFontColorEditor.setText(_fromUtf8(""))
        self.methodFontColorEditor.setObjectName(_fromUtf8("methodFontColorEditor"))
        self.gridLayout_13.addWidget(self.methodFontColorEditor, 1, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBoxFontColorEditor)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_13.addWidget(self.label_9, 1, 2, 1, 1)
        self.decorFontColorEditor = QgsColorButton(self.groupBoxFontColorEditor)
        self.decorFontColorEditor.setText(_fromUtf8(""))
        self.decorFontColorEditor.setObjectName(_fromUtf8("decorFontColorEditor"))
        self.gridLayout_13.addWidget(self.decorFontColorEditor, 1, 3, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBoxFontColorEditor)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_13.addWidget(self.label_10, 1, 4, 1, 1)
        self.commentFontColorEditor = QgsColorButton(self.groupBoxFontColorEditor)
        self.commentFontColorEditor.setText(_fromUtf8(""))
        self.commentFontColorEditor.setObjectName(_fromUtf8("commentFontColorEditor"))
        self.gridLayout_13.addWidget(self.commentFontColorEditor, 1, 5, 1, 1)
        self.label_12 = QtGui.QLabel(self.groupBoxFontColorEditor)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_13.addWidget(self.label_12, 2, 0, 1, 1)
        self.commentBlockFontColorEditor = QgsColorButton(self.groupBoxFontColorEditor)
        self.commentBlockFontColorEditor.setText(_fromUtf8(""))
        self.commentBlockFontColorEditor.setObjectName(_fromUtf8("commentBlockFontColorEditor"))
        self.gridLayout_13.addWidget(self.commentBlockFontColorEditor, 2, 1, 1, 1)
        self.label_25 = QtGui.QLabel(self.groupBoxFontColorEditor)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_13.addWidget(self.label_25, 2, 2, 1, 1)
        self.cursorColorEditor = QgsColorButton(self.groupBoxFontColorEditor)
        self.cursorColorEditor.setText(_fromUtf8(""))
        self.cursorColorEditor.setObjectName(_fromUtf8("cursorColorEditor"))
        self.gridLayout_13.addWidget(self.cursorColorEditor, 2, 3, 1, 1)
        self.label_23 = QtGui.QLabel(self.groupBoxFontColorEditor)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_13.addWidget(self.label_23, 2, 4, 1, 1)
        self.caretLineColorEditor = QgsColorButton(self.groupBoxFontColorEditor)
        self.caretLineColorEditor.setText(_fromUtf8(""))
        self.caretLineColorEditor.setObjectName(_fromUtf8("caretLineColorEditor"))
        self.gridLayout_13.addWidget(self.caretLineColorEditor, 2, 5, 1, 1)
        self.label_32 = QtGui.QLabel(self.groupBoxFontColorEditor)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_13.addWidget(self.label_32, 3, 0, 1, 1)
        self.singleQuoteFontColorEditor = QgsColorButton(self.groupBoxFontColorEditor)
        self.singleQuoteFontColorEditor.setText(_fromUtf8(""))
        self.singleQuoteFontColorEditor.setObjectName(_fromUtf8("singleQuoteFontColorEditor"))
        self.gridLayout_13.addWidget(self.singleQuoteFontColorEditor, 3, 1, 1, 1)
        self.label_33 = QtGui.QLabel(self.groupBoxFontColorEditor)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_13.addWidget(self.label_33, 3, 2, 1, 1)
        self.doubleQuoteFontColorEditor = QgsColorButton(self.groupBoxFontColorEditor)
        self.doubleQuoteFontColorEditor.setText(_fromUtf8(""))
        self.doubleQuoteFontColorEditor.setObjectName(_fromUtf8("doubleQuoteFontColorEditor"))
        self.gridLayout_13.addWidget(self.doubleQuoteFontColorEditor, 3, 3, 1, 1)
        self.label_34 = QtGui.QLabel(self.groupBoxFontColorEditor)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_13.addWidget(self.label_34, 3, 4, 1, 1)
        self.tripleSingleQuoteFontColorEditor = QgsColorButton(self.groupBoxFontColorEditor)
        self.tripleSingleQuoteFontColorEditor.setText(_fromUtf8(""))
        self.tripleSingleQuoteFontColorEditor.setObjectName(_fromUtf8("tripleSingleQuoteFontColorEditor"))
        self.gridLayout_13.addWidget(self.tripleSingleQuoteFontColorEditor, 3, 5, 1, 1)
        self.label_35 = QtGui.QLabel(self.groupBoxFontColorEditor)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_13.addWidget(self.label_35, 4, 0, 1, 1)
        self.tripleDoubleQuoteFontColorEditor = QgsColorButton(self.groupBoxFontColorEditor)
        self.tripleDoubleQuoteFontColorEditor.setText(_fromUtf8(""))
        self.tripleDoubleQuoteFontColorEditor.setObjectName(_fromUtf8("tripleDoubleQuoteFontColorEditor"))
        self.gridLayout_13.addWidget(self.tripleDoubleQuoteFontColorEditor, 4, 1, 1, 1)
        self.label_21 = QtGui.QLabel(self.groupBoxFontColorEditor)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_13.addWidget(self.label_21, 4, 4, 1, 1)
        self.paperBackgroundColorEditor = QgsColorButton(self.groupBoxFontColorEditor)
        self.paperBackgroundColorEditor.setText(_fromUtf8(""))
        self.paperBackgroundColorEditor.setObjectName(_fromUtf8("paperBackgroundColorEditor"))
        self.gridLayout_13.addWidget(self.paperBackgroundColorEditor, 4, 5, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_13, 1, 0, 1, 1)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.resetFontColorEditor = QtGui.QToolButton(self.groupBoxFontColorEditor)
        self.resetFontColorEditor.setText(_fromUtf8(""))
        self.resetFontColorEditor.setAutoRaise(True)
        self.resetFontColorEditor.setObjectName(_fromUtf8("resetFontColorEditor"))
        self.verticalLayout_5.addWidget(self.resetFontColorEditor)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.gridLayout_14.addLayout(self.verticalLayout_5, 1, 1, 1, 1)
        self.gridLayout_10.addWidget(self.groupBoxFontColorEditor, 2, 0, 1, 1)
        self.groupBox_5 = QgsCollapsibleGroupBox(self.groupBox_3)
        self.groupBox_5.setProperty("collapsed", True)
        self.groupBox_5.setProperty("saveCollapsedState", True)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_12 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.autoCloseBracketEditor = QtGui.QCheckBox(self.groupBox_5)
        self.autoCloseBracketEditor.setObjectName(_fromUtf8("autoCloseBracketEditor"))
        self.verticalLayout_3.addWidget(self.autoCloseBracketEditor)
        self.autoInsertionImportEditor = QtGui.QCheckBox(self.groupBox_5)
        self.autoInsertionImportEditor.setObjectName(_fromUtf8("autoInsertionImportEditor"))
        self.verticalLayout_3.addWidget(self.autoInsertionImportEditor)
        self.gridLayout_12.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_5, 4, 0, 1, 1)
        self.groupBoxAutoCompletionEditor = QgsCollapsibleGroupBox(self.groupBox_3)
        self.groupBoxAutoCompletionEditor.setCheckable(True)
        self.groupBoxAutoCompletionEditor.setChecked(True)
        self.groupBoxAutoCompletionEditor.setProperty("collapsed", True)
        self.groupBoxAutoCompletionEditor.setProperty("saveCheckedState", True)
        self.groupBoxAutoCompletionEditor.setProperty("saveCollapsedState", True)
        self.groupBoxAutoCompletionEditor.setObjectName(_fromUtf8("groupBoxAutoCompletionEditor"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBoxAutoCompletionEditor)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.layoutRadioButtonEditor = QtGui.QGridLayout()
        self.layoutRadioButtonEditor.setObjectName(_fromUtf8("layoutRadioButtonEditor"))
        self.autoCompFromDocEditor = QtGui.QRadioButton(self.groupBoxAutoCompletionEditor)
        self.autoCompFromDocEditor.setObjectName(_fromUtf8("autoCompFromDocEditor"))
        self.layoutRadioButtonEditor.addWidget(self.autoCompFromDocEditor, 0, 0, 1, 1)
        self.autoCompFromDocAPIEditor = QtGui.QRadioButton(self.groupBoxAutoCompletionEditor)
        self.autoCompFromDocAPIEditor.setObjectName(_fromUtf8("autoCompFromDocAPIEditor"))
        self.layoutRadioButtonEditor.addWidget(self.autoCompFromDocAPIEditor, 0, 2, 1, 1)
        self.autoCompFromAPIEditor = QtGui.QRadioButton(self.groupBoxAutoCompletionEditor)
        self.autoCompFromAPIEditor.setChecked(True)
        self.autoCompFromAPIEditor.setObjectName(_fromUtf8("autoCompFromAPIEditor"))
        self.layoutRadioButtonEditor.addWidget(self.autoCompFromAPIEditor, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.layoutRadioButtonEditor, 1, 0, 1, 2)
        self.label_2 = QtGui.QLabel(self.groupBoxAutoCompletionEditor)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_4.addWidget(self.label_2, 0, 0, 1, 1)
        self.autoCompThresholdEditor = QtGui.QSpinBox(self.groupBoxAutoCompletionEditor)
        self.autoCompThresholdEditor.setMaximum(10)
        self.autoCompThresholdEditor.setProperty("value", 2)
        self.autoCompThresholdEditor.setObjectName(_fromUtf8("autoCompThresholdEditor"))
        self.gridLayout_4.addWidget(self.autoCompThresholdEditor, 0, 1, 1, 1)
        self.gridLayout_10.addWidget(self.groupBoxAutoCompletionEditor, 3, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_9 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.groupBox_4 = QgsCollapsibleGroupBox(self.groupBox)
        self.groupBox_4.setProperty("collapsed", True)
        self.groupBox_4.setProperty("saveCollapsedState", True)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_11 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.autoCloseBracket = QtGui.QCheckBox(self.groupBox_4)
        self.autoCloseBracket.setObjectName(_fromUtf8("autoCloseBracket"))
        self.verticalLayout_2.addWidget(self.autoCloseBracket)
        self.autoInsertionImport = QtGui.QCheckBox(self.groupBox_4)
        self.autoInsertionImport.setObjectName(_fromUtf8("autoInsertionImport"))
        self.verticalLayout_2.addWidget(self.autoInsertionImport)
        self.gridLayout_11.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_4, 2, 0, 1, 1)
        self.groupBoxAutoCompletion = QgsCollapsibleGroupBox(self.groupBox)
        self.groupBoxAutoCompletion.setCheckable(True)
        self.groupBoxAutoCompletion.setChecked(True)
        self.groupBoxAutoCompletion.setProperty("collapsed", False)
        self.groupBoxAutoCompletion.setProperty("saveCheckedState", True)
        self.groupBoxAutoCompletion.setProperty("saveCollapsedState", True)
        self.groupBoxAutoCompletion.setObjectName(_fromUtf8("groupBoxAutoCompletion"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBoxAutoCompletion)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_6 = QtGui.QLabel(self.groupBoxAutoCompletion)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_5.addWidget(self.label_6, 0, 0, 1, 1)
        self.autoCompThreshold = QtGui.QSpinBox(self.groupBoxAutoCompletion)
        self.autoCompThreshold.setMaximum(10)
        self.autoCompThreshold.setProperty("value", 2)
        self.autoCompThreshold.setObjectName(_fromUtf8("autoCompThreshold"))
        self.gridLayout_5.addWidget(self.autoCompThreshold, 0, 1, 1, 1)
        self.layoutRadioButton = QtGui.QGridLayout()
        self.layoutRadioButton.setObjectName(_fromUtf8("layoutRadioButton"))
        self.autoCompFromDocAPI = QtGui.QRadioButton(self.groupBoxAutoCompletion)
        self.autoCompFromDocAPI.setObjectName(_fromUtf8("autoCompFromDocAPI"))
        self.layoutRadioButton.addWidget(self.autoCompFromDocAPI, 0, 2, 1, 1)
        self.autoCompFromAPI = QtGui.QRadioButton(self.groupBoxAutoCompletion)
        self.autoCompFromAPI.setChecked(True)
        self.autoCompFromAPI.setObjectName(_fromUtf8("autoCompFromAPI"))
        self.layoutRadioButton.addWidget(self.autoCompFromAPI, 0, 1, 1, 1)
        self.autoCompFromDoc = QtGui.QRadioButton(self.groupBoxAutoCompletion)
        self.autoCompFromDoc.setObjectName(_fromUtf8("autoCompFromDoc"))
        self.layoutRadioButton.addWidget(self.autoCompFromDoc, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.layoutRadioButton, 1, 0, 1, 2)
        self.gridLayout_9.addWidget(self.groupBoxAutoCompletion, 1, 0, 1, 1)
        self.groupBoxFontColor = QgsCollapsibleGroupBox(self.groupBox)
        self.groupBoxFontColor.setProperty("collapsed", True)
        self.groupBoxFontColor.setProperty("saveCollapsedState", True)
        self.groupBoxFontColor.setObjectName(_fromUtf8("groupBoxFontColor"))
        self.gridLayout_15 = QtGui.QGridLayout(self.groupBoxFontColor)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.groupBoxFontColor)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.fontComboBox = QtGui.QFontComboBox(self.groupBoxFontColor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fontComboBox.sizePolicy().hasHeightForWidth())
        self.fontComboBox.setSizePolicy(sizePolicy)
        self.fontComboBox.setInsertPolicy(QtGui.QComboBox.NoInsert)
        self.fontComboBox.setObjectName(_fromUtf8("fontComboBox"))
        self.horizontalLayout.addWidget(self.fontComboBox)
        self.label_3 = QtGui.QLabel(self.groupBoxFontColor)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        self.spinBox = QtGui.QSpinBox(self.groupBoxFontColor)
        self.spinBox.setMinimumSize(QtCore.QSize(51, 26))
        self.spinBox.setMaximumSize(QtCore.QSize(51, 26))
        self.spinBox.setMinimum(6)
        self.spinBox.setMaximum(15)
        self.spinBox.setProperty("value", 10)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.horizontalLayout.addWidget(self.spinBox)
        self.gridLayout_15.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label_16 = QtGui.QLabel(self.groupBoxFontColor)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_8.addWidget(self.label_16, 0, 0, 1, 1)
        self.defaultFontColor = QgsColorButton(self.groupBoxFontColor)
        self.defaultFontColor.setText(_fromUtf8(""))
        self.defaultFontColor.setObjectName(_fromUtf8("defaultFontColor"))
        self.gridLayout_8.addWidget(self.defaultFontColor, 0, 1, 1, 1)
        self.label_17 = QtGui.QLabel(self.groupBoxFontColor)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_8.addWidget(self.label_17, 0, 2, 1, 1)
        self.keywordFontColor = QgsColorButton(self.groupBoxFontColor)
        self.keywordFontColor.setText(_fromUtf8(""))
        self.keywordFontColor.setObjectName(_fromUtf8("keywordFontColor"))
        self.gridLayout_8.addWidget(self.keywordFontColor, 0, 3, 1, 1)
        self.label_26 = QtGui.QLabel(self.groupBoxFontColor)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_8.addWidget(self.label_26, 0, 4, 1, 1)
        self.classFontColor = QgsColorButton(self.groupBoxFontColor)
        self.classFontColor.setText(_fromUtf8(""))
        self.classFontColor.setObjectName(_fromUtf8("classFontColor"))
        self.gridLayout_8.addWidget(self.classFontColor, 0, 5, 1, 1)
        self.label_13 = QtGui.QLabel(self.groupBoxFontColor)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_8.addWidget(self.label_13, 1, 0, 1, 1)
        self.methodFontColor = QgsColorButton(self.groupBoxFontColor)
        self.methodFontColor.setText(_fromUtf8(""))
        self.methodFontColor.setObjectName(_fromUtf8("methodFontColor"))
        self.gridLayout_8.addWidget(self.methodFontColor, 1, 1, 1, 1)
        self.label_18 = QtGui.QLabel(self.groupBoxFontColor)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_8.addWidget(self.label_18, 1, 2, 1, 1)
        self.decorFontColor = QgsColorButton(self.groupBoxFontColor)
        self.decorFontColor.setText(_fromUtf8(""))
        self.decorFontColor.setObjectName(_fromUtf8("decorFontColor"))
        self.gridLayout_8.addWidget(self.decorFontColor, 1, 3, 1, 1)
        self.label_19 = QtGui.QLabel(self.groupBoxFontColor)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_8.addWidget(self.label_19, 1, 4, 1, 1)
        self.commentFontColor = QgsColorButton(self.groupBoxFontColor)
        self.commentFontColor.setText(_fromUtf8(""))
        self.commentFontColor.setObjectName(_fromUtf8("commentFontColor"))
        self.gridLayout_8.addWidget(self.commentFontColor, 1, 5, 1, 1)
        self.label_20 = QtGui.QLabel(self.groupBoxFontColor)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_8.addWidget(self.label_20, 2, 0, 1, 1)
        self.commentBlockFontColor = QgsColorButton(self.groupBoxFontColor)
        self.commentBlockFontColor.setText(_fromUtf8(""))
        self.commentBlockFontColor.setObjectName(_fromUtf8("commentBlockFontColor"))
        self.gridLayout_8.addWidget(self.commentBlockFontColor, 2, 1, 1, 1)
        self.label_24 = QtGui.QLabel(self.groupBoxFontColor)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_8.addWidget(self.label_24, 2, 2, 1, 1)
        self.cursorColor = QgsColorButton(self.groupBoxFontColor)
        self.cursorColor.setText(_fromUtf8(""))
        self.cursorColor.setObjectName(_fromUtf8("cursorColor"))
        self.gridLayout_8.addWidget(self.cursorColor, 2, 3, 1, 1)
        self.label_22 = QtGui.QLabel(self.groupBoxFontColor)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_8.addWidget(self.label_22, 2, 4, 1, 1)
        self.caretLineColor = QgsColorButton(self.groupBoxFontColor)
        self.caretLineColor.setText(_fromUtf8(""))
        self.caretLineColor.setObjectName(_fromUtf8("caretLineColor"))
        self.gridLayout_8.addWidget(self.caretLineColor, 2, 5, 1, 1)
        self.label_28 = QtGui.QLabel(self.groupBoxFontColor)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_8.addWidget(self.label_28, 3, 0, 1, 1)
        self.singleQuoteFontColor = QgsColorButton(self.groupBoxFontColor)
        self.singleQuoteFontColor.setText(_fromUtf8(""))
        self.singleQuoteFontColor.setObjectName(_fromUtf8("singleQuoteFontColor"))
        self.gridLayout_8.addWidget(self.singleQuoteFontColor, 3, 1, 1, 1)
        self.label_31 = QtGui.QLabel(self.groupBoxFontColor)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_8.addWidget(self.label_31, 3, 2, 1, 1)
        self.doubleQuoteFontColor = QgsColorButton(self.groupBoxFontColor)
        self.doubleQuoteFontColor.setText(_fromUtf8(""))
        self.doubleQuoteFontColor.setObjectName(_fromUtf8("doubleQuoteFontColor"))
        self.gridLayout_8.addWidget(self.doubleQuoteFontColor, 3, 3, 1, 1)
        self.label_29 = QtGui.QLabel(self.groupBoxFontColor)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_8.addWidget(self.label_29, 3, 4, 1, 1)
        self.tripleSingleQuoteFontColor = QgsColorButton(self.groupBoxFontColor)
        self.tripleSingleQuoteFontColor.setText(_fromUtf8(""))
        self.tripleSingleQuoteFontColor.setObjectName(_fromUtf8("tripleSingleQuoteFontColor"))
        self.gridLayout_8.addWidget(self.tripleSingleQuoteFontColor, 3, 5, 1, 1)
        self.label_30 = QtGui.QLabel(self.groupBoxFontColor)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_8.addWidget(self.label_30, 4, 0, 1, 1)
        self.tripleDoubleQuoteFontColor = QgsColorButton(self.groupBoxFontColor)
        self.tripleDoubleQuoteFontColor.setText(_fromUtf8(""))
        self.tripleDoubleQuoteFontColor.setObjectName(_fromUtf8("tripleDoubleQuoteFontColor"))
        self.gridLayout_8.addWidget(self.tripleDoubleQuoteFontColor, 4, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.groupBoxFontColor)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_8.addWidget(self.label_15, 4, 4, 1, 1)
        self.paperBackgroundColor = QgsColorButton(self.groupBoxFontColor)
        self.paperBackgroundColor.setText(_fromUtf8(""))
        self.paperBackgroundColor.setObjectName(_fromUtf8("paperBackgroundColor"))
        self.gridLayout_8.addWidget(self.paperBackgroundColor, 4, 5, 1, 1)
        self.label_14 = QtGui.QLabel(self.groupBoxFontColor)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_8.addWidget(self.label_14, 5, 4, 1, 1)
        self.stderrFontColor = QgsColorButton(self.groupBoxFontColor)
        self.stderrFontColor.setText(_fromUtf8(""))
        self.stderrFontColor.setObjectName(_fromUtf8("stderrFontColor"))
        self.gridLayout_8.addWidget(self.stderrFontColor, 5, 5, 1, 1)
        self.gridLayout_15.addLayout(self.gridLayout_8, 1, 0, 1, 1)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.resetFontColor = QtGui.QToolButton(self.groupBoxFontColor)
        self.resetFontColor.setText(_fromUtf8(""))
        self.resetFontColor.setAutoRaise(True)
        self.resetFontColor.setObjectName(_fromUtf8("resetFontColor"))
        self.verticalLayout_4.addWidget(self.resetFontColor)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.gridLayout_15.addLayout(self.verticalLayout_4, 1, 1, 1, 1)
        self.gridLayout_9.addWidget(self.groupBoxFontColor, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_6.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(SettingsDialogPythonConsole)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), SettingsDialogPythonConsole.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), SettingsDialogPythonConsole.reject)
        QtCore.QMetaObject.connectSlotsByName(SettingsDialogPythonConsole)

    def retranslateUi(self, SettingsDialogPythonConsole):
        self.groupBox_2.setTitle(_translate("SettingsDialogPythonConsole", "APIs", None))
        self.preloadAPI.setText(_translate("SettingsDialogPythonConsole", "Using preloaded APIs file", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("SettingsDialogPythonConsole", "APIs", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("SettingsDialogPythonConsole", "Path", None))
        self.groupBoxPreparedAPI.setTitle(_translate("SettingsDialogPythonConsole", "Using prepared APIs file", None))
        self.compileAPIs.setText(_translate("SettingsDialogPythonConsole", "Compile APIs...", None))
        self.groupBox_3.setTitle(_translate("SettingsDialogPythonConsole", "Editor", None))
        self.autoSaveScript.setText(_translate("SettingsDialogPythonConsole", "Auto-save script before running", None))
        self.enableObjectInspector.setText(_translate("SettingsDialogPythonConsole", "Enable Object Inspector (switching between tabs may be slow)", None))
        self.groupBoxFontColorEditor.setTitle(_translate("SettingsDialogPythonConsole", "Font and Colors", None))
        self.label_4.setText(_translate("SettingsDialogPythonConsole", "Font", None))
        self.label_5.setText(_translate("SettingsDialogPythonConsole", "Size", None))
        self.label_7.setText(_translate("SettingsDialogPythonConsole", "Default:", None))
        self.label_8.setText(_translate("SettingsDialogPythonConsole", "Keyword:", None))
        self.label_27.setText(_translate("SettingsDialogPythonConsole", "Class name:", None))
        self.label_11.setText(_translate("SettingsDialogPythonConsole", "Function:", None))
        self.label_9.setText(_translate("SettingsDialogPythonConsole", "Decorator:", None))
        self.label_10.setText(_translate("SettingsDialogPythonConsole", "Comment:", None))
        self.label_12.setText(_translate("SettingsDialogPythonConsole", "Comment block:", None))
        self.label_25.setText(_translate("SettingsDialogPythonConsole", "Cursor:", None))
        self.label_23.setText(_translate("SettingsDialogPythonConsole", "Caretline:", None))
        self.label_32.setText(_translate("SettingsDialogPythonConsole", "Single quote:", None))
        self.label_33.setText(_translate("SettingsDialogPythonConsole", "Double quote:", None))
        self.label_34.setText(_translate("SettingsDialogPythonConsole", "Triple single quote:", None))
        self.label_35.setText(_translate("SettingsDialogPythonConsole", "Triple double quote:", None))
        self.label_21.setText(_translate("SettingsDialogPythonConsole", "Background:", None))
        self.resetFontColorEditor.setToolTip(_translate("SettingsDialogPythonConsole", "Reset to default colors", None))
        self.groupBox_5.setTitle(_translate("SettingsDialogPythonConsole", "Typing", None))
        self.autoCloseBracketEditor.setText(_translate("SettingsDialogPythonConsole", "Automatic parentheses insertion", None))
        self.autoInsertionImportEditor.setText(_translate("SettingsDialogPythonConsole", "Automatic insertion of the \'import\' string on \'from xxx\'", None))
        self.groupBoxAutoCompletionEditor.setTitle(_translate("SettingsDialogPythonConsole", "Autocompletion", None))
        self.autoCompFromDocEditor.setToolTip(_translate("SettingsDialogPythonConsole", "Get autocompletion from current document", None))
        self.autoCompFromDocEditor.setText(_translate("SettingsDialogPythonConsole", "from Document", None))
        self.autoCompFromDocAPIEditor.setToolTip(_translate("SettingsDialogPythonConsole", "Get autocompletion from current document and installed APIs", None))
        self.autoCompFromDocAPIEditor.setText(_translate("SettingsDialogPythonConsole", "from Doc and APIs", None))
        self.autoCompFromAPIEditor.setToolTip(_translate("SettingsDialogPythonConsole", "Get autocompletion from installed APIs", None))
        self.autoCompFromAPIEditor.setText(_translate("SettingsDialogPythonConsole", "from APIs files", None))
        self.label_2.setText(_translate("SettingsDialogPythonConsole", "Autocompletion threshold", None))
        self.groupBox.setTitle(_translate("SettingsDialogPythonConsole", "Console", None))
        self.groupBox_4.setTitle(_translate("SettingsDialogPythonConsole", "Typing", None))
        self.autoCloseBracket.setText(_translate("SettingsDialogPythonConsole", "Automatic parentheses insertion", None))
        self.autoInsertionImport.setText(_translate("SettingsDialogPythonConsole", "Automatic insertion of the \'import\' string on \'from xxx\'", None))
        self.groupBoxAutoCompletion.setTitle(_translate("SettingsDialogPythonConsole", "Autocompletion", None))
        self.label_6.setText(_translate("SettingsDialogPythonConsole", "Autocompletion threshold", None))
        self.autoCompFromDocAPI.setToolTip(_translate("SettingsDialogPythonConsole", "Get autocompletion from current document and installed APIs", None))
        self.autoCompFromDocAPI.setText(_translate("SettingsDialogPythonConsole", "from Doc and APIs", None))
        self.autoCompFromAPI.setToolTip(_translate("SettingsDialogPythonConsole", "Get autocompletion from installed APIs", None))
        self.autoCompFromAPI.setText(_translate("SettingsDialogPythonConsole", "from APIs files", None))
        self.autoCompFromDoc.setToolTip(_translate("SettingsDialogPythonConsole", "Get autocompletion from current document", None))
        self.autoCompFromDoc.setText(_translate("SettingsDialogPythonConsole", "from Document", None))
        self.groupBoxFontColor.setTitle(_translate("SettingsDialogPythonConsole", "Font and Colors", None))
        self.label.setText(_translate("SettingsDialogPythonConsole", "Font", None))
        self.label_3.setText(_translate("SettingsDialogPythonConsole", "Size", None))
        self.label_16.setText(_translate("SettingsDialogPythonConsole", "Default:", None))
        self.label_17.setText(_translate("SettingsDialogPythonConsole", "Keyword:", None))
        self.label_26.setText(_translate("SettingsDialogPythonConsole", "Class name:", None))
        self.label_13.setText(_translate("SettingsDialogPythonConsole", "Function:", None))
        self.label_18.setText(_translate("SettingsDialogPythonConsole", "Decorator:", None))
        self.label_19.setText(_translate("SettingsDialogPythonConsole", "Comment:", None))
        self.label_20.setText(_translate("SettingsDialogPythonConsole", "Comment block:", None))
        self.label_24.setText(_translate("SettingsDialogPythonConsole", "Cursor:", None))
        self.label_22.setText(_translate("SettingsDialogPythonConsole", "Caretline:", None))
        self.label_28.setText(_translate("SettingsDialogPythonConsole", "Single quote:", None))
        self.label_31.setText(_translate("SettingsDialogPythonConsole", "Double quote:", None))
        self.label_29.setText(_translate("SettingsDialogPythonConsole", "Triple single quote:", None))
        self.label_30.setText(_translate("SettingsDialogPythonConsole", "Triple double quote:", None))
        self.label_15.setText(_translate("SettingsDialogPythonConsole", "Background:", None))
        self.label_14.setText(_translate("SettingsDialogPythonConsole", "Error:", None))
        self.resetFontColor.setToolTip(_translate("SettingsDialogPythonConsole", "Reset to default colors", None))

from qgis.gui import QgsColorButton, QgsCollapsibleGroupBox
