"The GRASS Development Team, the addon authors, further contributors and the user community have invested enormous efforts in making GRASS GIS available to you. Please give credit where credit is due and cite GRASS GIS and its addons when you use them for data analysis.\n"
"\n"
"For citation choices see below; for citing a particular GRASS GIS module, you may cite the main author(s) along with the GRASS Development Team.\n"
"\n"
"\n"
"Choices for citing the main GRASS GIS software (update YEAR and version number accordingly):\n"
"* GRASS Development Team, YEAR. Geographic Resources Analysis Support System (GRASS) Software, Version 7.2. Open Source Geospatial Foundation. http://grass.osgeo.org\n"
"* GRASS Development Team, YEAR. Geographic Resources Analysis Support System (GRASS) Programmer's Manual. Open Source Geospatial Foundation. Electronic document: http://grass.osgeo.org/programming7\n"
"\n"
"\n"
"Citing a GRASS GIS Addon (update AUTHOR(S), YEAR, Addon-NAME, and version number accordingly):\n"
"* AUTHOR(S), and GRASS Development Team, YEAR Addon-NAME. Geographic Resources Analysis Support System (GRASS) Software, Version 7.2. Open Source Geospatial Foundation. https://grass.osgeo.org/grass7/manuals/addons/Addon-NAME.html\n"
"\n"
"\n"
"For other (scientific) references, see\n"
"* https://grasswiki.osgeo.org/wiki/GRASS_Citation_Repository\n"
"\n"
"\n"
"A BibTeX entry for LaTeX users is:\n"
"\n"
"@Manual{GRASS_GIS_software,\n"
"  title = {Geographic Resources Analysis Support System (GRASS) Software, Version 7.2},\n"
"  author = {{GRASS Development Team}},\n"
"  organization = {Open Source Geospatial Foundation},\n"
"  address = {USA},\n"
"  year = {YEAR},\n"
"  url = {http://grass.osgeo.org},\n"
"}\n"
