del "%OSGEO4W_STARTMENU%\3Di Modeller Interface.lnk"
del "%OSGEO4W_STARTMENU%\QGIS Browser 3.4.4.lnk"
del "%OSGEO4W_STARTMENU%\Qt Designer with QGIS 3.4.4 custom widgets.lnk"
rmdir "%OSGEO4W_STARTMENU%"
del "%OSGEO4W_DESKTOP%\3Di Modeller Interface.lnk"
del "%OSGEO4W_DESKTOP%\QGIS Browser 3.4.4.lnk"
del "%OSGEO4W_DESKTOP%\Qt Designer with QGIS 3.4.4 custom widgets.lnk"
del "%OSGEO4W_DESKTOP%\OSGeo4W Shell.lnk"
rmdir "%OSGEO4W_DESKTOP%"
del "%OSGEO4W_ROOT%\bin\qgis-3di-ltr.bat"
del "%OSGEO4W_ROOT%\bin\qgis-bin-ltr.vars"
del "%OSGEO4W_ROOT%\bin\qgis-bin-ltr.env"
del "%OSGEO4W_ROOT%\bin\qgis-designer.bat"
del "%OSGEO4W_ROOT%\apps\qgis-ltr\python\qgis\qgisconfig.py"
del "%OSGEO4W_ROOT%\apps\qgis-ltr\bin\qgis-3di.reg"
del /s /q "%OSGEO4W_ROOT%\apps\qgis-ltr\python\*.pyc"
