rem del "%OSGEO4W_STARTMENU%\QGIS Desktop @version@ with GRASS @grassversion@.lnk"
rem del "%OSGEO4W_STARTMENU%\QGIS Browser @version@ with GRASS @grassversion@.lnk"
rem rmdir "%OSGEO4W_STARTMENU%"
rem del "%OSGEO4W_DESKTOP%\QGIS Desktop @version@ with GRASS @grassversion@.lnk"
rem del "%OSGEO4W_DESKTOP%\QGIS Browser @version@ with GRASS @grassversion@.lnk"
rem rmdir "%OSGEO4W_DESKTOP%"
rem del "%OSGEO4W_ROOT%\bin\@package@-grass@grassmajor@.bat"
rem del "%OSGEO4W_ROOT%\bin\@package@-bin-g@grassmajor@.exe"
rem del "%OSGEO4W_ROOT%\bin\@package@-bin-g@grassmajor@.vars"
rem del "%OSGEO4W_ROOT%\bin\@package@-bin-g@grassmajor@.env"
