# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/src/qgis/python/plugins/db_manager/ui/DlgQueryBuilder.ui'
#
# Created: Sat Jun 23 08:09:41 2018
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DbManagerQueryBuilderDlg(object):
    def setupUi(self, DbManagerQueryBuilderDlg):
        DbManagerQueryBuilderDlg.setObjectName(_fromUtf8("DbManagerQueryBuilderDlg"))
        DbManagerQueryBuilderDlg.resize(797, 463)
        self.verticalLayout_7 = QtGui.QVBoxLayout(DbManagerQueryBuilderDlg)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(DbManagerQueryBuilderDlg)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.col = QtGui.QTextEdit(DbManagerQueryBuilderDlg)
        self.col.setMinimumSize(QtCore.QSize(400, 0))
        self.col.setObjectName(_fromUtf8("col"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.col)
        self.label_2 = QtGui.QLabel(DbManagerQueryBuilderDlg)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.tab = QtGui.QLineEdit(DbManagerQueryBuilderDlg)
        self.tab.setFrame(True)
        self.tab.setObjectName(_fromUtf8("tab"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.tab)
        self.where = QtGui.QTextEdit(DbManagerQueryBuilderDlg)
        self.where.setObjectName(_fromUtf8("where"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.where)
        self.group = QtGui.QTextEdit(DbManagerQueryBuilderDlg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group.sizePolicy().hasHeightForWidth())
        self.group.setSizePolicy(sizePolicy)
        self.group.setMaximumSize(QtCore.QSize(16777215, 25))
        self.group.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.group.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.group.setObjectName(_fromUtf8("group"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.group)
        self.order = QtGui.QTextEdit(DbManagerQueryBuilderDlg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.order.sizePolicy().hasHeightForWidth())
        self.order.setSizePolicy(sizePolicy)
        self.order.setMaximumSize(QtCore.QSize(16777215, 25))
        self.order.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.order.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.order.setObjectName(_fromUtf8("order"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.order)
        self.label_3 = QtGui.QLabel(DbManagerQueryBuilderDlg)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtGui.QLabel(DbManagerQueryBuilderDlg)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtGui.QLabel(DbManagerQueryBuilderDlg)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_5)
        self.horizontalLayout_6.addLayout(self.formLayout)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.toolBox = QtGui.QToolBox(DbManagerQueryBuilderDlg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy)
        self.toolBox.setMinimumSize(QtCore.QSize(250, 0))
        self.toolBox.setMaximumSize(QtCore.QSize(250, 16777215))
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 250, 313))
        self.page.setObjectName(_fromUtf8("page"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.page)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.checkBox = QtGui.QCheckBox(self.page)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setKerning(True)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.verticalLayout_5.addWidget(self.checkBox)
        self.tables = QtGui.QComboBox(self.page)
        self.tables.setObjectName(_fromUtf8("tables"))
        self.tables.addItem(_fromUtf8(""))
        self.verticalLayout_5.addWidget(self.tables)
        self.columns = QtGui.QComboBox(self.page)
        self.columns.setObjectName(_fromUtf8("columns"))
        self.columns.addItem(_fromUtf8(""))
        self.verticalLayout_5.addWidget(self.columns)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.line_2 = QtGui.QFrame(self.page)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_5.addWidget(self.line_2)
        self.aggregates = QtGui.QComboBox(self.page)
        self.aggregates.setObjectName(_fromUtf8("aggregates"))
        self.aggregates.addItem(_fromUtf8(""))
        self.verticalLayout_5.addWidget(self.aggregates)
        self.functions = QtGui.QComboBox(self.page)
        self.functions.setObjectName(_fromUtf8("functions"))
        self.functions.addItem(_fromUtf8(""))
        self.verticalLayout_5.addWidget(self.functions)
        self.math = QtGui.QComboBox(self.page)
        self.math.setObjectName(_fromUtf8("math"))
        self.math.addItem(_fromUtf8(""))
        self.verticalLayout_5.addWidget(self.math)
        self.stringfct = QtGui.QComboBox(self.page)
        self.stringfct.setObjectName(_fromUtf8("stringfct"))
        self.stringfct.addItem(_fromUtf8(""))
        self.verticalLayout_5.addWidget(self.stringfct)
        self.operators = QtGui.QComboBox(self.page)
        self.operators.setObjectName(_fromUtf8("operators"))
        self.operators.addItem(_fromUtf8(""))
        self.verticalLayout_5.addWidget(self.operators)
        self.toolBox.addItem(self.page, _fromUtf8(""))
        self.page_2 = QtGui.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 250, 313))
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.page_2)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.columns_2 = QtGui.QComboBox(self.page_2)
        self.columns_2.setObjectName(_fromUtf8("columns_2"))
        self.columns_2.addItem(_fromUtf8(""))
        self.verticalLayout_6.addWidget(self.columns_2)
        self.extract = QtGui.QCheckBox(self.page_2)
        self.extract.setObjectName(_fromUtf8("extract"))
        self.verticalLayout_6.addWidget(self.extract)
        self.values = QtGui.QListView(self.page_2)
        self.values.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.values.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.values.setProperty("showDropIndicator", False)
        self.values.setDragEnabled(False)
        self.values.setDragDropMode(QtGui.QAbstractItemView.NoDragDrop)
        self.values.setObjectName(_fromUtf8("values"))
        self.verticalLayout_6.addWidget(self.values)
        self.toolBox.addItem(self.page_2, _fromUtf8(""))
        self.page_3 = QtGui.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 250, 313))
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.page_3)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.table_idx = QtGui.QComboBox(self.page_3)
        self.table_idx.setObjectName(_fromUtf8("table_idx"))
        self.table_idx.addItem(_fromUtf8(""))
        self.verticalLayout_8.addWidget(self.table_idx)
        self.table_target = QtGui.QComboBox(self.page_3)
        self.table_target.setObjectName(_fromUtf8("table_target"))
        self.table_target.addItem(_fromUtf8(""))
        self.verticalLayout_8.addWidget(self.table_target)
        self.usertree = QtGui.QPushButton(self.page_3)
        self.usertree.setObjectName(_fromUtf8("usertree"))
        self.verticalLayout_8.addWidget(self.usertree)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem1)
        self.toolBox.addItem(self.page_3, _fromUtf8(""))
        self.verticalLayout_4.addWidget(self.toolBox)
        self.horizontalLayout_6.addLayout(self.verticalLayout_4)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.reset = QtGui.QPushButton(DbManagerQueryBuilderDlg)
        self.reset.setObjectName(_fromUtf8("reset"))
        self.horizontalLayout_7.addWidget(self.reset)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.buttonBox = QtGui.QDialogButtonBox(DbManagerQueryBuilderDlg)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayout_7.addWidget(self.buttonBox)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)

        self.retranslateUi(DbManagerQueryBuilderDlg)
        self.toolBox.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), DbManagerQueryBuilderDlg.reject)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), DbManagerQueryBuilderDlg.accept)
        QtCore.QObject.connect(self.reset, QtCore.SIGNAL(_fromUtf8("clicked()")), self.where.clear)
        QtCore.QObject.connect(self.reset, QtCore.SIGNAL(_fromUtf8("clicked()")), self.tab.clear)
        QtCore.QObject.connect(self.reset, QtCore.SIGNAL(_fromUtf8("clicked()")), self.col.clear)
        QtCore.QObject.connect(self.reset, QtCore.SIGNAL(_fromUtf8("clicked()")), self.columns.clear)
        QtCore.QMetaObject.connectSlotsByName(DbManagerQueryBuilderDlg)

    def retranslateUi(self, DbManagerQueryBuilderDlg):
        DbManagerQueryBuilderDlg.setWindowTitle(_translate("DbManagerQueryBuilderDlg", "SQL query builder", None))
        self.label.setText(_translate("DbManagerQueryBuilderDlg", "Columns", None))
        self.label_2.setText(_translate("DbManagerQueryBuilderDlg", "Tables     ", None))
        self.label_3.setText(_translate("DbManagerQueryBuilderDlg", "Where    ", None))
        self.label_4.setText(_translate("DbManagerQueryBuilderDlg", "Group by", None))
        self.label_5.setText(_translate("DbManagerQueryBuilderDlg", "Order by", None))
        self.checkBox.setText(_translate("DbManagerQueryBuilderDlg", "Show system tables", None))
        self.tables.setItemText(0, _translate("DbManagerQueryBuilderDlg", "Tables", None))
        self.columns.setItemText(0, _translate("DbManagerQueryBuilderDlg", "Columns", None))
        self.aggregates.setItemText(0, _translate("DbManagerQueryBuilderDlg", "Aggregates", None))
        self.functions.setItemText(0, _translate("DbManagerQueryBuilderDlg", "Functions", None))
        self.math.setItemText(0, _translate("DbManagerQueryBuilderDlg", "Math", None))
        self.stringfct.setItemText(0, _translate("DbManagerQueryBuilderDlg", "Strings functions", None))
        self.operators.setItemText(0, _translate("DbManagerQueryBuilderDlg", "Operators", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("DbManagerQueryBuilderDlg", "Data", None))
        self.columns_2.setItemText(0, _translate("DbManagerQueryBuilderDlg", "Columns", None))
        self.extract.setText(_translate("DbManagerQueryBuilderDlg", "Only 10 first values", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("DbManagerQueryBuilderDlg", "Columns\' values", None))
        self.table_idx.setItemText(0, _translate("DbManagerQueryBuilderDlg", "Table (with spatial index)", None))
        self.table_target.setItemText(0, _translate("DbManagerQueryBuilderDlg", "Table (Target)", None))
        self.usertree.setText(_translate("DbManagerQueryBuilderDlg", "Use spatial index", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("DbManagerQueryBuilderDlg", "Spatial index", None))
        self.reset.setText(_translate("DbManagerQueryBuilderDlg", "&Reset", None))

