# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/src/qgis/python/plugins/db_manager/ui/DlgTableProperties.ui'
#
# Created: Sat Jun 23 08:09:42 2018
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DbManagerDlgTableProperties(object):
    def setupUi(self, DbManagerDlgTableProperties):
        DbManagerDlgTableProperties.setObjectName(_fromUtf8("DbManagerDlgTableProperties"))
        DbManagerDlgTableProperties.resize(547, 435)
        self.vboxlayout = QtGui.QVBoxLayout(DbManagerDlgTableProperties)
        self.vboxlayout.setObjectName(_fromUtf8("vboxlayout"))
        self.tabs = QtGui.QTabWidget(DbManagerDlgTableProperties)
        self.tabs.setObjectName(_fromUtf8("tabs"))
        self.tabColumns = QtGui.QWidget()
        self.tabColumns.setObjectName(_fromUtf8("tabColumns"))
        self.vboxlayout1 = QtGui.QVBoxLayout(self.tabColumns)
        self.vboxlayout1.setObjectName(_fromUtf8("vboxlayout1"))
        self.label = QtGui.QLabel(self.tabColumns)
        self.label.setObjectName(_fromUtf8("label"))
        self.vboxlayout1.addWidget(self.label)
        self.viewFields = QtGui.QTreeView(self.tabColumns)
        self.viewFields.setRootIsDecorated(False)
        self.viewFields.setObjectName(_fromUtf8("viewFields"))
        self.vboxlayout1.addWidget(self.viewFields)
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setObjectName(_fromUtf8("hboxlayout"))
        self.btnAddColumn = QtGui.QPushButton(self.tabColumns)
        self.btnAddColumn.setObjectName(_fromUtf8("btnAddColumn"))
        self.hboxlayout.addWidget(self.btnAddColumn)
        self.btnAddGeometryColumn = QtGui.QPushButton(self.tabColumns)
        self.btnAddGeometryColumn.setObjectName(_fromUtf8("btnAddGeometryColumn"))
        self.hboxlayout.addWidget(self.btnAddGeometryColumn)
        self.btnEditColumn = QtGui.QPushButton(self.tabColumns)
        self.btnEditColumn.setObjectName(_fromUtf8("btnEditColumn"))
        self.hboxlayout.addWidget(self.btnEditColumn)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem)
        self.btnDeleteColumn = QtGui.QPushButton(self.tabColumns)
        self.btnDeleteColumn.setObjectName(_fromUtf8("btnDeleteColumn"))
        self.hboxlayout.addWidget(self.btnDeleteColumn)
        self.vboxlayout1.addLayout(self.hboxlayout)
        self.tabs.addTab(self.tabColumns, _fromUtf8(""))
        self.tabConstraints = QtGui.QWidget()
        self.tabConstraints.setObjectName(_fromUtf8("tabConstraints"))
        self.vboxlayout2 = QtGui.QVBoxLayout(self.tabConstraints)
        self.vboxlayout2.setObjectName(_fromUtf8("vboxlayout2"))
        self.label_3 = QtGui.QLabel(self.tabConstraints)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.vboxlayout2.addWidget(self.label_3)
        self.viewConstraints = QtGui.QTreeView(self.tabConstraints)
        self.viewConstraints.setRootIsDecorated(False)
        self.viewConstraints.setObjectName(_fromUtf8("viewConstraints"))
        self.vboxlayout2.addWidget(self.viewConstraints)
        self.hboxlayout1 = QtGui.QHBoxLayout()
        self.hboxlayout1.setObjectName(_fromUtf8("hboxlayout1"))
        self.btnAddConstraint = QtGui.QPushButton(self.tabConstraints)
        self.btnAddConstraint.setObjectName(_fromUtf8("btnAddConstraint"))
        self.hboxlayout1.addWidget(self.btnAddConstraint)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout1.addItem(spacerItem1)
        self.btnDeleteConstraint = QtGui.QPushButton(self.tabConstraints)
        self.btnDeleteConstraint.setObjectName(_fromUtf8("btnDeleteConstraint"))
        self.hboxlayout1.addWidget(self.btnDeleteConstraint)
        self.vboxlayout2.addLayout(self.hboxlayout1)
        self.tabs.addTab(self.tabConstraints, _fromUtf8(""))
        self.tabIndexes = QtGui.QWidget()
        self.tabIndexes.setObjectName(_fromUtf8("tabIndexes"))
        self.vboxlayout3 = QtGui.QVBoxLayout(self.tabIndexes)
        self.vboxlayout3.setObjectName(_fromUtf8("vboxlayout3"))
        self.label_2 = QtGui.QLabel(self.tabIndexes)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.vboxlayout3.addWidget(self.label_2)
        self.viewIndexes = QtGui.QTreeView(self.tabIndexes)
        self.viewIndexes.setRootIsDecorated(False)
        self.viewIndexes.setObjectName(_fromUtf8("viewIndexes"))
        self.vboxlayout3.addWidget(self.viewIndexes)
        self.hboxlayout2 = QtGui.QHBoxLayout()
        self.hboxlayout2.setObjectName(_fromUtf8("hboxlayout2"))
        self.btnAddIndex = QtGui.QPushButton(self.tabIndexes)
        self.btnAddIndex.setObjectName(_fromUtf8("btnAddIndex"))
        self.hboxlayout2.addWidget(self.btnAddIndex)
        self.btnAddSpatialIndex = QtGui.QPushButton(self.tabIndexes)
        self.btnAddSpatialIndex.setObjectName(_fromUtf8("btnAddSpatialIndex"))
        self.hboxlayout2.addWidget(self.btnAddSpatialIndex)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout2.addItem(spacerItem2)
        self.btnDeleteIndex = QtGui.QPushButton(self.tabIndexes)
        self.btnDeleteIndex.setObjectName(_fromUtf8("btnDeleteIndex"))
        self.hboxlayout2.addWidget(self.btnDeleteIndex)
        self.vboxlayout3.addLayout(self.hboxlayout2)
        self.tabs.addTab(self.tabIndexes, _fromUtf8(""))
        self.vboxlayout.addWidget(self.tabs)
        self.buttonBox = QtGui.QDialogButtonBox(DbManagerDlgTableProperties)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.vboxlayout.addWidget(self.buttonBox)

        self.retranslateUi(DbManagerDlgTableProperties)
        self.tabs.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), DbManagerDlgTableProperties.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), DbManagerDlgTableProperties.reject)
        QtCore.QMetaObject.connectSlotsByName(DbManagerDlgTableProperties)
        DbManagerDlgTableProperties.setTabOrder(self.tabs, self.viewFields)
        DbManagerDlgTableProperties.setTabOrder(self.viewFields, self.btnAddColumn)
        DbManagerDlgTableProperties.setTabOrder(self.btnAddColumn, self.btnAddGeometryColumn)
        DbManagerDlgTableProperties.setTabOrder(self.btnAddGeometryColumn, self.btnEditColumn)
        DbManagerDlgTableProperties.setTabOrder(self.btnEditColumn, self.btnDeleteColumn)
        DbManagerDlgTableProperties.setTabOrder(self.btnDeleteColumn, self.viewConstraints)
        DbManagerDlgTableProperties.setTabOrder(self.viewConstraints, self.btnAddConstraint)
        DbManagerDlgTableProperties.setTabOrder(self.btnAddConstraint, self.btnDeleteConstraint)
        DbManagerDlgTableProperties.setTabOrder(self.btnDeleteConstraint, self.viewIndexes)
        DbManagerDlgTableProperties.setTabOrder(self.viewIndexes, self.btnAddIndex)
        DbManagerDlgTableProperties.setTabOrder(self.btnAddIndex, self.btnAddSpatialIndex)
        DbManagerDlgTableProperties.setTabOrder(self.btnAddSpatialIndex, self.btnDeleteIndex)
        DbManagerDlgTableProperties.setTabOrder(self.btnDeleteIndex, self.buttonBox)

    def retranslateUi(self, DbManagerDlgTableProperties):
        DbManagerDlgTableProperties.setWindowTitle(_translate("DbManagerDlgTableProperties", "Table properties", None))
        self.label.setText(_translate("DbManagerDlgTableProperties", "Table columns:", None))
        self.btnAddColumn.setText(_translate("DbManagerDlgTableProperties", "Add column", None))
        self.btnAddGeometryColumn.setText(_translate("DbManagerDlgTableProperties", "Add geometry column", None))
        self.btnEditColumn.setText(_translate("DbManagerDlgTableProperties", "Edit column", None))
        self.btnDeleteColumn.setText(_translate("DbManagerDlgTableProperties", "Delete column", None))
        self.tabs.setTabText(self.tabs.indexOf(self.tabColumns), _translate("DbManagerDlgTableProperties", "Columns", None))
        self.label_3.setText(_translate("DbManagerDlgTableProperties", "Primary, foreign keys, unique and check constraints:", None))
        self.btnAddConstraint.setText(_translate("DbManagerDlgTableProperties", "Add primary key / unique", None))
        self.btnDeleteConstraint.setText(_translate("DbManagerDlgTableProperties", "Delete constraint", None))
        self.tabs.setTabText(self.tabs.indexOf(self.tabConstraints), _translate("DbManagerDlgTableProperties", "Constraints", None))
        self.label_2.setText(_translate("DbManagerDlgTableProperties", "Indexes defined for this table:", None))
        self.btnAddIndex.setText(_translate("DbManagerDlgTableProperties", "Add index", None))
        self.btnAddSpatialIndex.setText(_translate("DbManagerDlgTableProperties", "Add spatial index", None))
        self.btnDeleteIndex.setText(_translate("DbManagerDlgTableProperties", "Delete index", None))
        self.tabs.setTabText(self.tabs.indexOf(self.tabIndexes), _translate("DbManagerDlgTableProperties", "Indexes", None))

